/**
 * synthesizeAnswer — shared retrieve→synthesize pipeline used by BOTH:
 *   - POST /knowledge/answer  (hub-protocol REST handler)
 *   - synap_ask MCP tool      (MCP adapter)
 *
 * Takes the raw `AskResult.answers` blocks, builds a compact context string,
 * calls the IS `/api/knowledge/answer` synthesis endpoint, and returns a
 * uniform result object. Falls back gracefully when the IS is unavailable.
 *
 * Callers own the HTTP response layer (c.json / return ok) — this function
 * returns a plain object so behaviour at both call sites stays byte-identical.
 */

import type { AskAnswer } from "./ask.js";
import { createLogger } from "@synap-core/core";
import { getDefaultActiveService } from "../../utils/intelligence-routing.js";
import { isCallBudgetMs } from "@synap/intelligence-client";
import {
  classifyAiFailure,
  type AiFailureClass,
} from "../../utils/ai-failure.js";

const logger = createLogger({ module: "knowledge-synthesize" });

export interface SynthesisSource {
  substrate: string;
  id: string;
  title: string;
}

export interface SynthesisResult {
  answer: string | null;
  sources: SynthesisSource[];
  /** Which substrates were queried (forwarded from AskResult). */
  routedTo: string[];
  /** Present only on IS unavailability — callers surface sources instead. */
  error?: "synthesis_unavailable";
  /**
   * WHY synthesis was unavailable, classified from the real error by the one
   * failure door (utils/ai-failure.ts). Present only alongside `error`, so a
   * caller can tell the user "the provider is out of credit, retrying will not
   * help" instead of inventing a temporary outage.
   */
  failureClass?: AiFailureClass;
}

const MAX_CONTEXT_CHARS = 40_000;
/** Per-snippet-field slice — generous enough to carry a real body/verdict/
 * conclusion instead of the old 300-char stub, while MAX_CONTEXT_CHARS still
 * bounds the total context sent to the IS. */
const MAX_FIELD_CHARS = 1500;
/**
 * Procedural rows (`knowledge_keys`) get a LARGER slice than an entity field.
 *
 * Measured, not guessed: with `MAX_FIELD_CHARS`, asking the pod "why is the
 * cost chokepoint in buildClient and not callCascade?" returned the runbook's
 * opening (what was built) and then said "the context does not explicitly
 * explain WHY" — because the WHY section sits ~1,800 chars into a ~4,000-char
 * note. A curated runbook is a whole document written to be recalled, not one
 * field of a record, and the answer-bearing part is routinely NOT the opening.
 * Procedural hits are also few (single digits) where entity hits are many, so
 * the extra budget lands where it buys the most and costs the least.
 *
 * `MAX_CONTEXT_CHARS` still bounds the total; it was raised alongside this so
 * a couple of long runbooks cannot silently push every other source out of the
 * context window (the loop DROPS remaining items once the cap is hit — a
 * budget too large is its own failure mode, just a quieter one).
 */
const MAX_PROCEDURAL_CHARS = 6_000;
/** Common JSONB `properties` keys that hold prose worth surfacing verbatim. */
const PROPERTY_TEXT_KEYS = [
  "content",
  "conclusion",
  "description",
  "summary",
  "body",
  "notes",
];

/**
 * Lead with an honest acknowledgment when the caller has matching pending
 * capture proposals — WITHOUT fabricating their content as fact. Guarded by a
 * substring check so we never double-prepend if the IS's own answer already
 * surfaced them.
 *
 * MUST come first, not last: `data.answer` is free-text generated by the IS
 * LLM (no hardcoded/flagged "nothing found" string exists to detect — see
 * `/api/knowledge/answer`'s system prompt), so a "no information found" style
 * opener is common and indistinguishable from real content by string-matching
 * alone. Appending the pending note AFTER such an opener meant the reader saw
 * "nothing" first and only self-corrected afterward. Leading with it instead
 * means a pending-only result never reads as a flat "no information found",
 * whether or not the IS's own text happened to be empty-shaped.
 */
function prependPendingNotice(answer: string, pendingCount: number): string {
  if (pendingCount <= 0 || /pending/i.test(answer)) return answer;
  const plural = pendingCount === 1 ? "" : "s";
  const verb = pendingCount === 1 ? "matches" : "match";
  return (
    `${pendingCount} pending proposal${plural} already ${verb} this — not yet ` +
    `in the graph; review them before treating this as unknown, and do NOT ` +
    `re-capture. ${answer}`
  );
}

/**
 * Build context + sources from retrieved answer blocks, then call the IS
 * synthesis endpoint. Returns a SynthesisResult regardless of IS availability.
 */
/**
 * Build the model-facing context block + the source list from raw substrate
 * answers. Extracted PURE (no network, no db) so the field-budget contract is
 * testable directly — the same reason `shapeAgentSpend` is pure in the event
 * repository. `synthesizeAnswer` is otherwise an IS round-trip and cannot be
 * asserted on cheaply.
 */
export function buildSynthesisContext(answers: AskAnswer[]): {
  sources: SynthesisSource[];
  context: string;
} {
  const sources: SynthesisSource[] = [];
  const contextParts: string[] = [];
  let contextLen = 0;

  for (const block of answers) {
    if (block.status !== "ok") continue;
    for (const item of block.items) {
      const rec = item as Record<string, unknown>;
      const id = typeof rec.id === "string" ? rec.id : "";
      const title =
        (typeof rec.name === "string" && rec.name) ||
        (typeof rec.title === "string" && rec.title) ||
        (typeof rec.claim === "string" && rec.claim) ||
        (typeof rec.fact === "string" && rec.fact) ||
        (typeof rec.content === "string" && rec.content) ||
        // Procedural rows (knowledge_keys) carry NONE of the above — their
        // human name is `key` ("namespace:slug"). Without this they fell all
        // the way through to the raw UUID, so every runbook source rendered as
        // an opaque id the reader (and the model) could not identify.
        (typeof rec.key === "string" && rec.key) ||
        id ||
        "(item)";

      if (id) sources.push({ substrate: block.substrate, id, title });

      // Snippet: title + the entity BODY + a few key string props. The body
      // is the fix — without it synthesis only ever saw title/metadata and
      // could never answer questions whose answer lives in the content.
      const snippetBits: string[] = [String(title)];

      // 1. The attached document body (retrieve.ts's `fetchOrdered` join) —
      //    the actual long-form content, not a metadata field.
      if (typeof rec.content === "string" && rec.content.trim()) {
        snippetBits.push(`content: ${rec.content.slice(0, MAX_FIELD_CHARS)}`);
      }

      // 1b. Procedural runbooks (knowledge_keys) keep their whole body in
      //     `value`. It is not `content` and not inside `properties`, so it
      //     used to fall through to the generic 300-char branch below — a
      //     runbook is routinely thousands of characters, so synthesis saw
      //     only its opening lines and would answer "I cannot find that"
      //     while holding the exact note that answered it. `value` IS the
      //     document here, so it gets the same budget `content` does.
      if (typeof rec.value === "string" && rec.value.trim()) {
        snippetBits.push(`value: ${rec.value.slice(0, MAX_PROCEDURAL_CHARS)}`);
      }

      // 2. Prose buried inside the JSONB `properties` object — previously
      //    dropped entirely because it's an object, not a top-level string.
      if (rec.properties && typeof rec.properties === "object") {
        const props = rec.properties as Record<string, unknown>;
        for (const key of PROPERTY_TEXT_KEYS) {
          const v = props[key];
          if (typeof v === "string" && v.trim()) {
            snippetBits.push(`${key}: ${v.slice(0, MAX_FIELD_CHARS)}`);
          }
        }
      }

      // 3. Fall back to other short top-level string props (pre-existing
      //    behavior), skipping fields already handled above.
      for (const [k, v] of Object.entries(rec)) {
        if (
          ["id", "name", "title", "content", "properties", "value"].includes(k)
        )
          continue;
        if (typeof v === "string" && v.trim()) {
          snippetBits.push(`${k}: ${v.slice(0, 300)}`);
        }
        if (snippetBits.length >= 8) break;
      }
      const entry = `- [${block.substrate}] ${snippetBits.join(" · ")}`;
      if (contextLen + entry.length > MAX_CONTEXT_CHARS) break;
      contextParts.push(entry);
      contextLen += entry.length + 1;
    }
    if (contextLen >= MAX_CONTEXT_CHARS) break;
  }

  return { sources, context: contextParts.join("\n") };
}

export async function synthesizeAnswer(
  answers: AskAnswer[],
  question: string,
  routedTo: string[],
  workspaceId: string | null | undefined,
  /**
   * Count of the caller's OWN pending capture proposals that text-matched this
   * query (`AskResult.pending.matches.length`). The IS composes `answer` from
   * `answers` alone — it never sees the pending lane, so a query with matching
   * pending proposals but nothing in the graph yet came back "no information
   * found" sitting right next to a non-empty pending block: a self-contradiction.
   * When >0, we PREPEND one acknowledgment sentence to the synthesized answer
   * (unless it already mentions pending) — never fabricating pending CONTENT as
   * fact, just pointing at the block below. Leading (not trailing) matters: the
   * IS answer is free text with no detectable "nothing found" flag, so a
   * negative-sounding opener must never be the first thing the reader sees when
   * pending matches exist. Optional/defaults to 0 so other callers of
   * synthesizeAnswer are unaffected.
   */
  pendingCount = 0
): Promise<SynthesisResult> {
  const { sources, context } = buildSynthesisContext(answers);

  // Call the IS "answer" door — one focused LLM call. Resolve the IS endpoint +
  // the pod's PER-CONNECTION key from the DB (registered IS), NEVER from env.
  let isUrl = "";
  try {
    const { endpoint, apiKey } = await getDefaultActiveService();
    isUrl = endpoint;
    const res = await fetch(`${isUrl}/api/knowledge/answer`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-API-Key": apiKey,
      },
      body: JSON.stringify({
        question,
        context,
        workspaceId: workspaceId ?? undefined,
      }),
      // `generation` budget, not a literal. This is a model call (the IS
      // synthesizes an answer over retrieved context), so it carries the same
      // reasoning-model exposure as the 2026-07-31 incident — and its `context`
      // grows with corpus size, exactly the variable that made 60s bite there.
      signal: AbortSignal.timeout(isCallBudgetMs("generation")),
    });
    if (!res.ok) throw new Error(`IS answer HTTP ${res.status}`);
    const data = (await res.json()) as { answer?: string };
    const answer =
      typeof data.answer === "string"
        ? prependPendingNotice(data.answer, pendingCount)
        : null;
    return {
      answer,
      sources,
      routedTo,
    };
  } catch (err) {
    // Synthesis unavailable — return sources so callers can still show matches.
    // Log the real cause: this is a pod→IS transport/auth/route failure (the IS
    // returns 200 even on LLM errors), NOT an LLM failure — without this line the
    // cause (ECONNREFUSED / 401 key drift / 404 stale-route) is invisible.
    logger.error(
      { err, isUrl },
      "knowledge synthesis call to IS failed — returning sources without answer"
    );
    return {
      answer: null,
      sources,
      routedTo,
      error: "synthesis_unavailable",
      failureClass: classifyAiFailure(err),
    };
  }
}
