/**
 * /admin/bootstrap — one-time token bootstrap for first self-hosted admin.
 *
 * Flow:
 * 1) User enters bootstrap token + admin email
 * 2) API creates a one-time pod invite for that email
 * 3) User is redirected to Kratos registration browser flow
 */
import { useState } from "react";
import { API_URL } from "../lib/trpc";

function registrationBrowserUrl(): string {
  const base = API_URL.replace(/\/$/, "");
  const returnTo = encodeURIComponent(`${window.location.origin}/admin/`);
  return `${base}/.ory/kratos/public/self-service/registration/browser?return_to=${returnTo}`;
}

export default function BootstrapAdminPage() {
  const [token, setToken] = useState("");
  const [email, setEmail] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const onSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!token.trim() || !email.trim()) {
      setError("Token and email are required.");
      return;
    }
    setBusy(true);
    setError(null);
    try {
      const res = await fetch(`${API_URL}/api/admin/bootstrap/claim`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: JSON.stringify({
          token: token.trim(),
          email: email.trim(),
          role: "admin",
        }),
      });
      const data = (await res.json().catch(() => ({}))) as {
        error?: string;
      };
      if (!res.ok) {
        setError(data.error ?? `Bootstrap failed (${res.status})`);
        return;
      }
      window.location.assign(registrationBrowserUrl());
    } catch (err) {
      setError(err instanceof Error ? err.message : "Bootstrap failed");
    } finally {
      setBusy(false);
    }
  };

  return (
    <div className="flex min-h-screen items-center justify-center bg-background p-6">
      <form
        onSubmit={onSubmit}
        className="w-full max-w-md rounded-2xl border border-divider bg-content1 p-6 shadow-xl"
      >
        <h1 className="text-xl font-bold text-foreground">
          Bootstrap first admin
        </h1>
        <p className="mt-1 text-small text-default-500">
          Use the one-time token generated by the install CLI, then create your
          admin account.
        </p>

        {error ? (
          <div className="mt-4 rounded-medium border border-danger-200 bg-danger-50 p-3 text-sm text-danger-800">
            {error}
          </div>
        ) : null}

        <div className="mt-6 flex flex-col gap-4">
          <div className="flex flex-col gap-1">
            <label className="text-sm font-medium text-default-700">
              Bootstrap token
            </label>
            <input
              className="rounded-md border border-default-200 bg-background px-3 py-2 text-sm text-foreground outline-none focus:border-amber-500"
              value={token}
              onChange={(ev) => setToken(ev.target.value)}
              autoComplete="off"
              spellCheck={false}
              required
            />
          </div>
          <div className="flex flex-col gap-1">
            <label className="text-sm font-medium text-default-700">
              Admin email
            </label>
            <input
              type="email"
              className="rounded-md border border-default-200 bg-background px-3 py-2 text-sm text-foreground outline-none focus:border-amber-500"
              value={email}
              onChange={(ev) => setEmail(ev.target.value)}
              autoComplete="email"
              required
            />
          </div>
        </div>

        <button
          type="submit"
          disabled={busy}
          className="mt-6 w-full rounded-md bg-foreground px-4 py-2 text-sm font-semibold text-background disabled:opacity-60"
        >
          {busy ? "Preparing registration..." : "Continue to registration"}
        </button>
      </form>
    </div>
  );
}
