/**
 * Server-side tRPC caller — the HUMAN door to this pod.
 *
 * WHY tRPC AND NOT `/api/hub/*`: `/api/hub` is the AGENT protocol (IS↔Backend)
 * and its auth middleware accepts `Authorization: Bearer` or `X-Session-Token`
 * only — it never reads the Kratos COOKIE a browser session holds. tRPC is the
 * cookie-authenticated door every other Pod Admin surface already uses, so this
 * is the canonical path for a human browser app, not a way around a locked one.
 *
 * WHY RAW HTTP AND NOT THE TYPED CLIENT: `@synap-core/api-types` ships a
 * COMMITTED, generated `AppRouter` (`src/generated.d.ts`), regenerated by the
 * contracts-publish pipeline. A newly added procedure is invisible to the typed
 * client until that shared artifact is regenerated, which is a release step and
 * not something to do from inside a feature change. The wire format is stable
 * and small; the response shapes are declared in
 * `app/(admin)/marketplace/_lib/types.ts`.
 *
 * SuperJSON is the pod's transformer (see `app/providers.tsx`), hence the
 * `{ json }` envelope in both directions.
 */

const INTERNAL_POD_URL = (
  process.env.POD_URL ?? "http://localhost:4000"
).replace(/\/$/, "");

export type PodCallResult<T> =
  | { ok: true; data: T }
  | { ok: false; status: number; message: string; code?: string };

/**
 * Call one tRPC mutation as the cookie-bearing operator.
 *
 * Errors are RETURNED, never thrown and never flattened into a boolean. A
 * caller that cannot tell "the pod refused" from "the pod never answered" is
 * exactly how an install that landed once reported "failed: Unknown error".
 */
export async function callPodMutation<T>(
  procedure: string,
  input: unknown,
  cookie: string
): Promise<PodCallResult<T>> {
  let res: Response;
  try {
    res = await fetch(`${INTERNAL_POD_URL}/trpc/${procedure}`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
        Cookie: cookie,
      },
      body: JSON.stringify({ json: input }),
      cache: "no-store",
    });
  } catch {
    return { ok: false, status: 502, message: "Could not reach this pod." };
  }

  const text = await res.text();
  let body: unknown;
  try {
    body = JSON.parse(text);
  } catch {
    return {
      ok: false,
      status: res.status,
      message: text.slice(0, 400) || `Pod returned ${res.status}.`,
    };
  }

  // tRPC answers 200 with `{result:{data:{json}}}`, and a failure with
  // `{error:{json:{message,code,data:{httpStatus}}}}` — a NON-2xx status too,
  // but read the envelope rather than inferring the outcome from the status.
  const envelope = body as {
    result?: { data?: { json?: T } };
    error?: {
      json?: {
        message?: string;
        code?: string;
        data?: { httpStatus?: number };
      };
    };
  };

  if (envelope.error) {
    const err = envelope.error.json;
    return {
      ok: false,
      status: err?.data?.httpStatus ?? res.status,
      message: err?.message ?? `Pod returned ${res.status}.`,
      code: err?.code,
    };
  }

  if (!res.ok) {
    return {
      ok: false,
      status: res.status,
      message: `Pod returned ${res.status}.`,
    };
  }

  // `data.json` is absent when the procedure returned undefined. That is
  // "the pod reported nothing", not success — say so rather than inventing a
  // result the producer never wrote.
  if (!envelope.result || envelope.result.data?.json === undefined) {
    return {
      ok: false,
      status: 502,
      message: "The pod accepted the call but returned no result.",
    };
  }

  return { ok: true, data: envelope.result.data.json as T };
}
