/**
 * Door tool-name table — the PURE builder (no fs, no sibling imports).
 *
 * A pod MCP tool reaches an agent through three doors, each under its own name:
 *   - `pod-mcp`       the pod's own `/mcp` (`synap_define_kind`)
 *   - `cp-connector`  the claude.ai Control-Plane connector, which re-advertises a
 *                     curated subset as `pod__<short>` (`pod__define_kind`)
 *   - `raycast`       the Raycast extension's AI tools (`define-kind`)
 *
 * The CP and Raycast manifests live in SIBLING repos the pod must never import at
 * runtime, so `gen-door-tool-names.ts` reads them at generation time, calls this
 * builder, and commits the result as `door-tool-names.generated.ts`. The freshness
 * tripwire (`door-tool-names.freshness.test.ts`) re-runs this SAME builder against
 * the siblings and fails when the committed table is stale. One builder, two call
 * sites — never a second derivation.
 */

export type SkillDoor = "pod-mcp" | "cp-connector" | "raycast";

export interface DoorToolNameRow {
  "pod-mcp": string;
  /** `null` = not curated on the CP connector. */
  "cp-connector": string | null;
  /** `null` = not a Raycast tool (a catalog gap with no covering tool). */
  raycast: string | null;
}

export interface DoorToolNameInputs {
  /** Tool names from the pod's committed `mcp-tools.manifest.json`. */
  podToolNames: string[];
  /** Source text of `synap-control-plane-api/src/routes/mcp-pod-tools.ts`. */
  cpCuratedSource: string;
  /** Parsed `synap-raycast/scripts/mcp-raycast-catalog.json`. */
  raycastCatalog: {
    allowlist: Array<{ podToolName: string; name: string }>;
    extras: string[];
    gaps: Record<string, string>;
  };
}

/** CP connector namespace prefix (`synap-control-plane-api/src/routes/mcp.ts` POD_TOOL_PREFIX). */
const CP_PREFIX = "pod__";

/**
 * `{ name: "define_kind", podToolName: "synap_define_kind" }` pairs out of the CP
 * curated catalog. Fails loudly when a `podToolName:` line was NOT paired — a
 * reformat of that file must break generation, never silently shrink the table.
 */
export function parseCpCuratedPairs(source: string): Map<string, string> {
  const pairs = new Map<string, string>();
  const re = /name:\s*"([a-z_]+)",\s*podToolName:\s*"(synap_[a-z_]+)"/g;
  for (const m of source.matchAll(re)) pairs.set(m[2]!, m[1]!);
  const declared = source.match(/podToolName:\s*"synap_[a-z_]+"/g)?.length ?? 0;
  if (declared === 0 || pairs.size !== declared) {
    throw new Error(
      `CP curated catalog parse: paired ${pairs.size} of ${declared} podToolName entries — the source shape changed; fix parseCpCuratedPairs.`
    );
  }
  return pairs;
}

/**
 * A Raycast catalog gap whose reason starts `COVERED —` names the Raycast tool
 * that covers it (e.g. `synap_get_relations` → extra `get-connections`). The
 * covering tool is the first word of the reason that IS a Raycast tool name.
 */
function raycastCoveringTool(
  reason: string,
  raycastNames: Set<string>
): string | null {
  if (!/^COVERED\b/.test(reason)) return null;
  for (const word of reason.match(/[a-z][a-z-]*/g) ?? []) {
    if (raycastNames.has(word)) return word;
  }
  return null;
}

export function buildDoorToolNames(
  inputs: DoorToolNameInputs
): Record<string, DoorToolNameRow> {
  const cp = parseCpCuratedPairs(inputs.cpCuratedSource);
  const raycastDirect = new Map(
    inputs.raycastCatalog.allowlist.map((r) => [r.podToolName, r.name])
  );
  const raycastNames = new Set([
    ...inputs.raycastCatalog.allowlist.map((r) => r.name),
    ...inputs.raycastCatalog.extras,
  ]);

  const table: Record<string, DoorToolNameRow> = {};
  for (const podTool of [...inputs.podToolNames].sort()) {
    const short = cp.get(podTool);
    const gap = inputs.raycastCatalog.gaps[podTool];
    table[podTool] = {
      "pod-mcp": podTool,
      "cp-connector": short ? `${CP_PREFIX}${short}` : null,
      raycast:
        raycastDirect.get(podTool) ??
        (gap ? raycastCoveringTool(gap, raycastNames) : null),
    };
  }
  return table;
}

/** The committed module text. Deterministic: same inputs → byte-identical output. */
export function renderDoorToolNamesModule(
  table: Record<string, DoorToolNameRow>
): string {
  const rows = Object.entries(table)
    .map(
      ([tool, row]) =>
        `  ${tool}: { "pod-mcp": ${JSON.stringify(row["pod-mcp"])}, "cp-connector": ${JSON.stringify(row["cp-connector"])}, raycast: ${JSON.stringify(row.raycast)} },`
    )
    .join("\n");
  return `// GENERATED by src/routers/mcp/gen-door-tool-names.ts — DO NOT EDIT.
// Regenerate: cd packages/api && npx tsx src/routers/mcp/gen-door-tool-names.ts
// Sources: mcp-tools.manifest.json, synap-control-plane-api/src/routes/mcp-pod-tools.ts,
// synap-raycast/scripts/mcp-raycast-catalog.json. Freshness: door-tool-names.freshness.test.ts.
import type { DoorToolNameRow } from "./door-tool-names.build.js";

export const DOOR_TOOL_NAMES: Record<string, DoorToolNameRow> = {
${rows}
};
`;
}
