// GENERATED by src/routers/mcp/gen-door-tool-names.ts — DO NOT EDIT.
// Regenerate: cd packages/api && npx tsx src/routers/mcp/gen-door-tool-names.ts
// Sources: mcp-tools.manifest.json, synap-control-plane-api/src/routes/mcp-pod-tools.ts,
// synap-raycast/scripts/mcp-raycast-catalog.json. Freshness: door-tool-names.freshness.test.ts.
import type { DoorToolNameRow } from "./door-tool-names.build.js";

export const DOOR_TOOL_NAMES: Record<string, DoorToolNameRow> = {
  synap_ask: {
    "pod-mcp": "synap_ask",
    "cp-connector": "pod__ask",
    raycast: "ask",
  },
  synap_attach_facet: {
    "pod-mcp": "synap_attach_facet",
    "cp-connector": "pod__attach_facet",
    raycast: "attach-role",
  },
  synap_capture: {
    "pod-mcp": "synap_capture",
    "cp-connector": "pod__capture",
    raycast: "capture",
  },
  synap_complete_session: {
    "pod-mcp": "synap_complete_session",
    "cp-connector": null,
    raycast: null,
  },
  synap_create_automation: {
    "pod-mcp": "synap_create_automation",
    "cp-connector": "pod__create_automation",
    raycast: "create-automation",
  },
  synap_create_cell: {
    "pod-mcp": "synap_create_cell",
    "cp-connector": "pod__create_cell",
    raycast: "create-cell",
  },
  synap_create_document: {
    "pod-mcp": "synap_create_document",
    "cp-connector": "pod__create_document",
    raycast: null,
  },
  synap_create_entity: {
    "pod-mcp": "synap_create_entity",
    "cp-connector": "pod__create_entity",
    raycast: "create-entity",
  },
  synap_create_playbook: {
    "pod-mcp": "synap_create_playbook",
    "cp-connector": "pod__create_playbook",
    raycast: "create-playbook",
  },
  synap_create_project: {
    "pod-mcp": "synap_create_project",
    "cp-connector": null,
    raycast: "create-project",
  },
  synap_create_rule: {
    "pod-mcp": "synap_create_rule",
    "cp-connector": null,
    raycast: null,
  },
  synap_create_skill: {
    "pod-mcp": "synap_create_skill",
    "cp-connector": null,
    raycast: null,
  },
  synap_create_verb: {
    "pod-mcp": "synap_create_verb",
    "cp-connector": null,
    raycast: null,
  },
  synap_create_view: {
    "pod-mcp": "synap_create_view",
    "cp-connector": null,
    raycast: "create-view",
  },
  synap_create_workspace: {
    "pod-mcp": "synap_create_workspace",
    "cp-connector": "pod__create_workspace",
    raycast: "create-workspace",
  },
  synap_declare_workspace_source: {
    "pod-mcp": "synap_declare_workspace_source",
    "cp-connector": null,
    raycast: null,
  },
  synap_define_kind: {
    "pod-mcp": "synap_define_kind",
    "cp-connector": "pod__define_kind",
    raycast: "define-kind",
  },
  synap_define_role: {
    "pod-mcp": "synap_define_role",
    "cp-connector": "pod__define_role",
    raycast: "define-role",
  },
  synap_detach_facet: {
    "pod-mcp": "synap_detach_facet",
    "cp-connector": null,
    raycast: null,
  },
  synap_diagnose: {
    "pod-mcp": "synap_diagnose",
    "cp-connector": "pod__diagnose",
    raycast: "diagnose",
  },
  synap_export_project_pack: {
    "pod-mcp": "synap_export_project_pack",
    "cp-connector": null,
    raycast: null,
  },
  synap_get_channel: {
    "pod-mcp": "synap_get_channel",
    "cp-connector": null,
    raycast: null,
  },
  synap_get_document: {
    "pod-mcp": "synap_get_document",
    "cp-connector": "pod__get_document",
    raycast: "get-entity",
  },
  synap_get_entities: {
    "pod-mcp": "synap_get_entities",
    "cp-connector": "pod__get_entities",
    raycast: "get-recent",
  },
  synap_get_entity: {
    "pod-mcp": "synap_get_entity",
    "cp-connector": "pod__get_entity",
    raycast: "get-entity",
  },
  synap_get_graph: {
    "pod-mcp": "synap_get_graph",
    "cp-connector": "pod__get_graph",
    raycast: "get-connections",
  },
  synap_get_project: {
    "pod-mcp": "synap_get_project",
    "cp-connector": null,
    raycast: null,
  },
  synap_get_relations: {
    "pod-mcp": "synap_get_relations",
    "cp-connector": null,
    raycast: "get-connections",
  },
  synap_get_session: {
    "pod-mcp": "synap_get_session",
    "cp-connector": null,
    raycast: null,
  },
  synap_get_thread_context: {
    "pod-mcp": "synap_get_thread_context",
    "cp-connector": "pod__get_thread_context",
    raycast: null,
  },
  synap_governance: {
    "pod-mcp": "synap_governance",
    "cp-connector": null,
    raycast: null,
  },
  synap_link_entities: {
    "pod-mcp": "synap_link_entities",
    "cp-connector": "pod__link_entities",
    raycast: "create-relation",
  },
  synap_list_automations: {
    "pod-mcp": "synap_list_automations",
    "cp-connector": "pod__list_automations",
    raycast: "list-automations",
  },
  synap_list_capabilities: {
    "pod-mcp": "synap_list_capabilities",
    "cp-connector": "pod__list_capabilities",
    raycast: "list-capabilities",
  },
  synap_list_playbooks: {
    "pod-mcp": "synap_list_playbooks",
    "cp-connector": "pod__list_playbooks",
    raycast: "list-playbooks",
  },
  synap_list_profiles: {
    "pod-mcp": "synap_list_profiles",
    "cp-connector": "pod__list_profiles",
    raycast: "list-profiles",
  },
  synap_list_projects: {
    "pod-mcp": "synap_list_projects",
    "cp-connector": null,
    raycast: null,
  },
  synap_list_proposals: {
    "pod-mcp": "synap_list_proposals",
    "cp-connector": "pod__list_proposals",
    raycast: null,
  },
  synap_list_sessions: {
    "pod-mcp": "synap_list_sessions",
    "cp-connector": null,
    raycast: null,
  },
  synap_list_views: {
    "pod-mcp": "synap_list_views",
    "cp-connector": null,
    raycast: "list-views",
  },
  synap_list_widgets: {
    "pod-mcp": "synap_list_widgets",
    "cp-connector": null,
    raycast: "list-widgets",
  },
  synap_list_workspaces: {
    "pod-mcp": "synap_list_workspaces",
    "cp-connector": null,
    raycast: null,
  },
  synap_load_skill: {
    "pod-mcp": "synap_load_skill",
    "cp-connector": "pod__load_skill",
    raycast: "load-skill",
  },
  synap_match_playbooks: {
    "pod-mcp": "synap_match_playbooks",
    "cp-connector": "pod__match_playbooks",
    raycast: null,
  },
  synap_orient: {
    "pod-mcp": "synap_orient",
    "cp-connector": "pod__orient",
    raycast: "orient",
  },
  synap_post_message: {
    "pod-mcp": "synap_post_message",
    "cp-connector": "pod__post_message",
    raycast: "send-to-channel",
  },
  synap_project_use_workspace: {
    "pod-mcp": "synap_project_use_workspace",
    "cp-connector": null,
    raycast: null,
  },
  synap_promote_cell_to_renderer: {
    "pod-mcp": "synap_promote_cell_to_renderer",
    "cp-connector": null,
    raycast: null,
  },
  synap_promote_session_to_playbook: {
    "pod-mcp": "synap_promote_session_to_playbook",
    "cp-connector": null,
    raycast: null,
  },
  synap_reject_proposal: {
    "pod-mcp": "synap_reject_proposal",
    "cp-connector": null,
    raycast: null,
  },
  synap_remember_fact: {
    "pod-mcp": "synap_remember_fact",
    "cp-connector": "pod__remember_fact",
    raycast: null,
  },
  synap_rerun_session: {
    "pod-mcp": "synap_rerun_session",
    "cp-connector": "pod__rerun_session",
    raycast: null,
  },
  synap_resolve_identity: {
    "pod-mcp": "synap_resolve_identity",
    "cp-connector": "pod__resolve_identity",
    raycast: "capture",
  },
  synap_revert_session: {
    "pod-mcp": "synap_revert_session",
    "cp-connector": null,
    raycast: null,
  },
  synap_revise_proposal: {
    "pod-mcp": "synap_revise_proposal",
    "cp-connector": null,
    raycast: null,
  },
  synap_run_capability: {
    "pod-mcp": "synap_run_capability",
    "cp-connector": "pod__run_capability",
    raycast: "run-action",
  },
  synap_run_playbook: {
    "pod-mcp": "synap_run_playbook",
    "cp-connector": "pod__run_playbook",
    raycast: "run-playbook",
  },
  synap_set_project_focus: {
    "pod-mcp": "synap_set_project_focus",
    "cp-connector": "pod__set_project_focus",
    raycast: null,
  },
  synap_set_workspace_focus: {
    "pod-mcp": "synap_set_workspace_focus",
    "cp-connector": "pod__set_workspace_focus",
    raycast: null,
  },
  synap_start_session: {
    "pod-mcp": "synap_start_session",
    "cp-connector": null,
    raycast: "start-session",
  },
  synap_store_file: {
    "pod-mcp": "synap_store_file",
    "cp-connector": null,
    raycast: null,
  },
  synap_template_health: {
    "pod-mcp": "synap_template_health",
    "cp-connector": null,
    raycast: null,
  },
  synap_trigger_automation: {
    "pod-mcp": "synap_trigger_automation",
    "cp-connector": "pod__trigger_automation",
    raycast: null,
  },
  synap_update_entity: {
    "pod-mcp": "synap_update_entity",
    "cp-connector": "pod__update_entity",
    raycast: "update-entity",
  },
  synap_update_project: {
    "pod-mcp": "synap_update_project",
    "cp-connector": null,
    raycast: null,
  },
  synap_update_session: {
    "pod-mcp": "synap_update_session",
    "cp-connector": null,
    raycast: null,
  },
};
