/**
 * Events Schema - The Immutable Source of Truth
 * 
 * This table stores every event that happens in the system.
 * Events are NEVER updated or deleted, only appended.
 * 
 * Multi-dialect compatible (SQLite + PostgreSQL)
 */

import { randomUUID } from 'crypto';

// Import based on DB_DIALECT
const isPostgres = process.env.DB_DIALECT === 'postgres';

let events: any;

if (isPostgres) {
  // PostgreSQL schema
  const { pgTable, uuid, timestamp, jsonb, text } = require('drizzle-orm/pg-core');
  
  events = pgTable('events', {
    // Primary key (UUID auto-generated by PostgreSQL)
    id: uuid('id').defaultRandom().primaryKey(),
    
    // When did this event occur?
    timestamp: timestamp('timestamp', { mode: 'date', withTimezone: true })
      .defaultNow()
      .notNull(),
    
    // What type of event is this?
    type: text('type').notNull(),
    
    // Event payload (JSONB for efficient queries)
    data: jsonb('data').notNull(),
    
    // Where did this event come from?
    source: text('source').default('api'),
    
    // For tracing related events
    correlationId: uuid('correlation_id'),
    
    // **NEW for Multi-User**: Which user does this event belong to?
    userId: text('user_id').notNull(),
  });
} else {
  // SQLite schema (for local/open-source version)
  const { sqliteTable, text, integer } = require('drizzle-orm/sqlite-core');
  
  events = sqliteTable('events', {
    // Primary key (UUID generated in app code)
    id: text('id').primaryKey().$defaultFn(() => randomUUID()),
    
    // When did this event occur? (Unix timestamp in ms)
    timestamp: integer('timestamp', { mode: 'timestamp_ms' })
      .$defaultFn(() => new Date())
      .notNull(),
    
    // What type of event is this?
    type: text('type').notNull(),
    
    // Event payload (JSON text)
    data: text('data', { mode: 'json' }).notNull(),
    
    // Where did this event come from?
    source: text('source').default('api'),
    
    // For tracing related events
    correlationId: text('correlation_id'),
    
    // Note: SQLite version doesn't have userId (single-user)
  });
}

export { events };

export type Event = typeof events.$inferSelect;
export type NewEvent = typeof events.$inferInsert;

