/**
 * Events Schema - The Immutable Source of Truth
 * 
 * This table stores every event that happens in the system.
 * Events are NEVER updated or deleted, only appended.
 * 
 * PostgreSQL-only schema with Row-Level Security (RLS) for multi-user support.
 */

import { pgTable, uuid, timestamp, jsonb, text } from 'drizzle-orm/pg-core';

export const events = pgTable('events', {
  // Primary key (UUID auto-generated by PostgreSQL)
  id: uuid('id').defaultRandom().primaryKey(),
  
  // When did this event occur?
  timestamp: timestamp('timestamp', { mode: 'date', withTimezone: true })
    .defaultNow()
    .notNull(),
  
  // What type of event is this?
  type: text('type').notNull(),
  
  // Event payload (JSONB for efficient queries)
  data: jsonb('data').notNull(),
  
  // Where did this event come from?
  source: text('source').default('api'),
  
  // For tracing related events
  correlationId: uuid('correlation_id'),
  
  // Which user does this event belong to?
  userId: text('user_id').notNull(),
});

export type Event = typeof events.$inferSelect;
export type NewEvent = typeof events.$inferInsert;
