/**
 * Events Schema - The Immutable Source of Truth
 *
 * This table stores every event that happens in the system.
 * Events are NEVER updated or deleted, only appended.
 *
 * Event Sourcing: Each event references a subject (the thing it's about)
 * via subjectId and subjectType. We can rebuild any subject's state by
 * replaying its events in order.
 *
 * PostgreSQL-only schema with Row-Level Security (RLS) for multi-user support.
 */

import {
  pgTable,
  uuid,
  timestamp,
  jsonb,
  text,
  index,
  primaryKey,
  boolean,
  integer,
  numeric,
} from "drizzle-orm/pg-core";

export const events = pgTable(
  "events",
  {
    // Primary key (UUID auto-generated by PostgreSQL)
    // Note: This is NOT a standalone primary key because TimescaleDB hypertables
    // require the partitioning column (timestamp) to be part of any unique/primary index.
    id: uuid("id").defaultRandom().notNull(),

    // When did this event occur? (for ordering and replay)
    timestamp: timestamp("timestamp", { mode: "date", withTimezone: true })
      .defaultNow()
      .notNull(),

    // What type of event is this?
    type: text("type").notNull(),

    // ✨ EVENT SOURCING: What is this event about?
    // subjectId: The ID of the thing this event affects (inbox item, entity, document, etc.)
    // subjectType: The type of subject (inbox_item, entity, note, task, document, etc.)
    subjectId: text("subject_id").notNull(),
    subjectType: text("subject_type").notNull(),

    // Event data payload - WHAT happened (JSONB for efficient queries)
    data: jsonb("data").notNull(),

    // Event metadata - HOW/WHY it happened (AI enrichment, import context, sync info, etc.)
    // This is the extensibility point - any intelligence or integration can add context here
    metadata: jsonb("metadata"),

    // Where did this event come from?
    source: text("source").default("api"),

    // For tracing related events
    correlationId: uuid("correlation_id"),

    // Which user does this event belong to?
    userId: text("user_id").notNull(),

    // ─── Agent-run observability telemetry (0131) ───────────────────────────
    // First-class columns (NOT jsonb) so an agentRun event — and any
    // agent-authored .completed event — carries authorship + cost/usage that
    // can be indexed and aggregated. All nullable: a non-agent / non-LLM event
    // simply leaves them NULL. cost is NULL when the provider does not report a
    // price (honest, never a fabricated 0).
    isAgent: boolean("is_agent"),
    agentUserId: text("agent_user_id"),
    agentType: text("agent_type"),
    model: text("model"),
    provider: text("provider"),
    costUsd: numeric("cost_usd", { precision: 12, scale: 6 }),
    tokensIn: integer("tokens_in"),
    tokensOut: integer("tokens_out"),
    tokensTotal: integer("tokens_total"),
    latencyMs: integer("latency_ms"),
    toolCount: integer("tool_count"),
    runStatus: text("run_status"),
    finishReason: text("finish_reason"),
  },
  (table) => ({
    // ✨ COMPOSITE PK: Required for TimescaleDB hypertable with primary key
    pk: primaryKey({ columns: [table.id, table.timestamp] }),

    // ✨ INDEX: For event sourcing queries - "get all events for this subject"
    subjectIdx: index("idx_events_subject").on(
      table.subjectType,
      table.subjectId,
      table.timestamp
    ),

    // INDEX: For querying by user and event type
    userTypeIdx: index("idx_events_user_type").on(table.userId, table.type),

    // INDEX: For time-based queries
    timestampIdx: index("idx_events_timestamp").on(table.timestamp),

    // INDEX: agent-run observability — "all runs by this agent" (0131)
    agentUserIdIdx: index("events_agent_user_id_idx").on(table.agentUserId),
  })
);

export type Event = typeof events.$inferSelect;
export type NewEvent = typeof events.$inferInsert;

import { createInsertSchema, createSelectSchema } from "drizzle-zod";

/**
 * @internal For monorepo usage - enables schema composition in API layer
 */
export const insertEventSchema = createInsertSchema(events);
/**
 * @internal For monorepo usage - enables schema composition in API layer
 */
export const selectEventSchema = createSelectSchema(events);
