/**
 * Provisioning Tokens Schema
 *
 * Stores one-time provisioning tokens for control-plane-provisioned backends
 * These tokens are generated by the control plane and passed to the backend during installation.
 * They can be used ONCE to create the first admin invitation, then are invalidated.
 *
 * Self-hosted backends don't have provisioning tokens, so the control plane cannot call them.
 */
import { pgTable, text, timestamp, uuid, index } from "drizzle-orm/pg-core";
export const provisioningTokens = pgTable(
  "provisioning_tokens",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tokenHash: text("token_hash").notNull().unique(), // SHA256 hash of token
    usedAt: timestamp("used_at", { mode: "date", withTimezone: true }),
    createdAt: timestamp("created_at", { mode: "date", withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => ({
    tokenHashIdx: index("idx_provisioning_tokens_token_hash").on(
      table.tokenHash
    ),
  })
);
//# sourceMappingURL=provisioning-tokens.js.map
