/**
 * Provisioning Tokens Schema
 *
 * Stores one-time provisioning tokens for control-plane-provisioned backends
 * These tokens are generated by the control plane and passed to the backend during installation.
 * They can be used ONCE to create the first admin invitation, then are invalidated.
 *
 * Self-hosted backends don't have provisioning tokens, so the control plane cannot call them.
 */
export declare const provisioningTokens: import("drizzle-orm/pg-core").PgTableWithColumns<{
  name: "provisioning_tokens";
  schema: undefined;
  columns: {
    id: import("drizzle-orm/pg-core").PgColumn<
      {
        name: "id";
        tableName: "provisioning_tokens";
        dataType: "string";
        columnType: "PgUUID";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: true;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
      },
      {},
      {}
    >;
    tokenHash: import("drizzle-orm/pg-core").PgColumn<
      {
        name: "token_hash";
        tableName: "provisioning_tokens";
        dataType: "string";
        columnType: "PgText";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: [string, ...string[]];
        baseColumn: never;
        identity: undefined;
        generated: undefined;
      },
      {},
      {}
    >;
    usedAt: import("drizzle-orm/pg-core").PgColumn<
      {
        name: "used_at";
        tableName: "provisioning_tokens";
        dataType: "date";
        columnType: "PgTimestamp";
        data: Date;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
      },
      {},
      {}
    >;
    createdAt: import("drizzle-orm/pg-core").PgColumn<
      {
        name: "created_at";
        tableName: "provisioning_tokens";
        dataType: "date";
        columnType: "PgTimestamp";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
      },
      {},
      {}
    >;
  };
  dialect: "pg";
}>;
export type ProvisioningToken = typeof provisioningTokens.$inferSelect;
export type NewProvisioningToken = typeof provisioningTokens.$inferInsert;
//# sourceMappingURL=provisioning-tokens.d.ts.map
