/**
 * Widget Definitions Schema
 *
 * Stores widget type definitions for the dynamic bento widget registry.
 * - workspaceId = null → system-wide built-in widgets
 * - workspaceId set → workspace-specific custom widgets (AI-generated or iframe)
 *
 * configSchema (JSONSchema) drives:
 *   1. IS config generation/validation
 *   2. Settings form auto-generation in the frontend
 */

import {
  pgTable,
  uuid,
  text,
  timestamp,
  jsonb,
  boolean,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { workspaces } from "./workspaces.js";

export type WidgetRendererType = "builtin" | "iframe" | "native" | "frame";

/**
 * Trust level of a widget/cell definition — the server-side authority for
 * whether a framed view's mutation may execute directly or must propose.
 *
 * Mirrors `AppTrustLevel` from `@synap-core/overlay-protocol`. Trust is
 * assigned by a human-approved event (marketplace install) — NEVER self-claimed
 * by the frame and NEVER taken from a request body.
 *
 *   - "trusted"   → first-party / user-authored: may act directly in-envelope.
 *   - "installed" → human-approved marketplace install: proposes.
 *   - "generated" → AI-generated, unreviewed: proposes (most conservative).
 *
 * Default is the most conservative ("generated") so an un-migrated or
 * unspecified row can never write directly.
 */
export type WidgetTrustLevel = "trusted" | "installed" | "generated";

export const widgetDefinitions = pgTable(
  "widget_definitions",
  {
    id: uuid("id").defaultRandom().primaryKey(),

    /** Unique type key within scope, e.g. "entity-list", "win-rate-gauge" */
    typeKey: text("type_key").notNull(),

    /**
     * NULL = system-wide (built-ins, seeded at startup).
     * Set = workspace-specific custom widget.
     */
    workspaceId: uuid("workspace_id").references(() => workspaces.id, {
      onDelete: "cascade",
    }),

    // ── Display ──────────────────────────────────────────────────────────

    name: text("name").notNull(),
    description: text("description"),

    /** Lucide icon name, e.g. "bar-chart-3" */
    icon: text("icon"),

    /** Grouping label: "core" | "data" | "ai" | "app-specific" */
    category: text("category"),

    // ── Renderer ─────────────────────────────────────────────────────────

    /** "builtin" = precompiled React component; "iframe" = sandboxed HTML */
    rendererType: text("renderer_type")
      .notNull()
      .default("builtin")
      .$type<WidgetRendererType>(),

    /**
     * Full HTML document for iframe widgets (includes SynapWidget SDK).
     * NULL for built-ins — they are resolved by the frontend cell registry.
     */
    rendererSource: text("renderer_source"),

    /**
     * Original JSX/TSX source code for native widgets.
     * Stored for editing — the compiled bundle is in bundleSource.
     * NULL for built-ins and iframe widgets.
     */
    source: text("source"),

    /**
     * Compiled IIFE bundle for native widgets.
     * Generated by the widget compiler from `source`.
     * The bundle reads shared deps from window.__SYNAP_MODULES__.
     * NULL for built-ins and iframe widgets.
     */
    bundleSource: text("bundle_source"),

    // ── Config schema ────────────────────────────────────────────────────

    /**
     * JSONSchema describing the per-instance config this widget accepts.
     * Stored as JSONB; used for IS config validation + settings form auto-gen.
     */
    configSchema: jsonb("config_schema")
      .$type<Record<string, unknown>>()
      .notNull()
      .default({}),

    /** Sensible defaults applied when a new block is created. */
    defaultConfig: jsonb("default_config")
      .$type<Record<string, unknown>>()
      .default({}),

    /** Default grid size in 12-column units. */
    defaultSize: jsonb("default_size")
      .$type<{ w: number; h: number }>()
      .notNull()
      .default({ w: 6, h: 4 }),

    /** Minimum grid size; optional. */
    minSize: jsonb("min_size").$type<{ w: number; h: number }>(),

    /**
     * npm package version pins for frame widgets.
     * e.g. { 'recharts': '2.12.0' }
     * NULL for non-frame widgets.
     */
    deps: jsonb("deps").$type<Record<string, string>>().default({}),

    // ── Lifecycle ────────────────────────────────────────────────────────

    isActive: boolean("is_active").notNull().default(true),
    version: text("version").default("1.0.0"),

    /**
     * Server-side trust authority for governing this definition's writes.
     * Set by the human-approved install/publish path, never self-claimed.
     * Conservative default: "generated" → a framed view always proposes
     * unless an approval event has elevated it.
     */
    trustLevel: text("trust_level")
      .notNull()
      .default("generated")
      .$type<WidgetTrustLevel>(),

    createdAt: timestamp("created_at", { mode: "date", withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", { mode: "date", withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => ({
    /** typeKey is unique within a workspace scope (null = system) */
    typeKeyWorkspaceUniq: uniqueIndex("widget_def_type_key_workspace_uniq").on(
      table.typeKey,
      table.workspaceId
    ),

    workspaceIdIdx: index("widget_def_workspace_id_idx").on(table.workspaceId),
    isActiveIdx: index("widget_def_is_active_idx").on(table.isActive),
  })
);

export type WidgetDefinition = typeof widgetDefinitions.$inferSelect;
export type NewWidgetDefinition = typeof widgetDefinitions.$inferInsert;
