import {
  eq,
  automationRuns,
  proposals,
  userVisibleWhere,
} from "@synap/database";
import type { SQL } from "drizzle-orm";

/**
 * Visibility WHERE for the two LEDGER source nodes — `runs_query`
 * (`automation_runs`) and `proposals_query` (`proposals`).
 *
 * WHY THIS IS NOT A LOCAL MIRROR (unlike `entity-query-scope.ts`): the entity
 * predicate had to be hand-duplicated in `@synap/jobs` because its SSOT
 * (`accessScopeWhere`) lives in `@synap/api`, which `@synap/jobs` may never
 * import (api depends on jobs). The ledger predicate is the SAME
 * `userVisibleWhere` the api listings use — so instead of a fourth copy, the
 * IMPLEMENTATION was moved into `@synap/database` (utils/user-visible-where.ts),
 * which both packages already depend on. This module is a thin, named,
 * TESTABLE binding of that shared predicate to the two ledger tables; it exists
 * so the visibility decision is one greppable place with one unit test, not an
 * inline expression buried in a 5000-line executor.
 *
 * THE PREDICATE, and why it is exactly this one:
 *   `userVisibleWhere(<table>.workspaceId, ownerId)` — byte-for-byte the
 *   predicate `listAutomationRuns` (packages/api services/runs/index.ts) and the
 *   `proposals` listing (packages/api routers/proposals.ts) apply to the same
 *   tables. Consistency with the existing listing is the explicit decision, NOT
 *   an accident: a report generated by one of these nodes and the Runs / review
 *   surfaces in the browser must never disagree about which runs or proposals
 *   exist. Deliberately NOT narrowed for pod-wide (`workspace_id IS NULL`) rows
 *   either — pod-wide proposals get the same handling as any proposal.
 *
 * `ownerId` is the automation's `createdBy` — the same read identity
 * `executeQueryStep` already derives.
 *
 * FAIL CLOSED: with no owner there is no user floor to apply, so the predicate
 * collapses to this workspace's own rows. An un-floored read of either ledger
 * would hand a run every other user's runs / proposals; narrowing to the
 * workspace the run is already authorized for is the safe degradation. (Unlike
 * `scope:'pod'` in the entity node, there is no owner-required mode here to
 * throw on — the workspace narrow is always a valid, non-leaking answer.)
 */
export function runsQueryVisibilityWhere(args: {
  workspaceId: string;
  ownerId?: string;
}): SQL {
  const { workspaceId, ownerId } = args;
  return ownerId
    ? userVisibleWhere(automationRuns.workspaceId, ownerId)
    : eq(automationRuns.workspaceId, workspaceId);
}

/** The `proposals` twin of {@link runsQueryVisibilityWhere}. Same contract. */
export function proposalsQueryVisibilityWhere(args: {
  workspaceId: string;
  ownerId?: string;
}): SQL {
  const { workspaceId, ownerId } = args;
  return ownerId
    ? userVisibleWhere(proposals.workspaceId, ownerId)
    : eq(proposals.workspaceId, workspaceId);
}
