/**
 * Admin Management Router
 *
 * Handles admin invitations and validation for control-plane-provisioned backends
 */

import { Hono } from "hono";
import { getDb } from "@synap/database";
import { adminInvitations, provisioningTokens } from "@synap/database/schema";
import { eq, and, gte, isNull } from "drizzle-orm";
import crypto from "crypto";
import { createLogger } from "@synap-core/core";

const logger = createLogger({ module: "admin-router" });

export const adminRouter = new Hono();

/**
 * Validate admin invitation token
 * GET /api/admin/validate-invite?token=...
 */
adminRouter.get("/validate-invite", async (c) => {
  const token = c.req.query("token");

  if (!token) {
    return c.json({ error: "Token required" }, 400);
  }

  const db = await getDb();
  const tokenHash = crypto.createHash("sha256").update(token).digest("hex");

  const invitation = await db.query.adminInvitations.findFirst({
    where: and(
      eq(adminInvitations.tokenHash, tokenHash),
      gte(adminInvitations.expiresAt, new Date()),
      isNull(adminInvitations.usedAt)
    ),
  });

  if (!invitation) {
    return c.json({ valid: false, error: "Invalid or expired token" }, 400);
  }

  return c.json({
    valid: true,
    email: invitation.email,
    backendDomain: invitation.backendDomain,
  });
});

/**
 * Create admin invitation (called by control plane)
 * POST /api/admin/invite
 *
 * Protected by one-time provisioning token (PROVISIONING_TOKEN)
 * This token is generated by the control plane and passed to the backend during installation.
 * It can only be used ONCE, then is invalidated.
 *
 * Self-hosted backends don't have this token, so this endpoint is unavailable to them.
 */
adminRouter.post("/invite", async (c) => {
  // Check for provisioning token (instead of shared API key)
  const providedToken = c.req.header("X-Provisioning-Token");
  const expectedToken = process.env.PROVISIONING_TOKEN;

  // Self-hosted backends don't have provisioning tokens
  if (!expectedToken) {
    logger.info(
      "Admin invitation endpoint called but no PROVISIONING_TOKEN configured (self-hosted backend)"
    );
    return c.json(
      {
        error:
          "This endpoint is only available for control-plane-provisioned backends",
      },
      403
    );
  }

  if (!providedToken) {
    logger.warn("Provisioning token required but not provided");
    return c.json({ error: "Provisioning token required" }, 401);
  }

  // Validate token matches
  if (providedToken !== expectedToken) {
    logger.warn("Invalid provisioning token provided");
    return c.json({ error: "Invalid provisioning token" }, 401);
  }

  // Check if token has already been used
  const db = await getDb();
  const provisioningTokenHash = crypto
    .createHash("sha256")
    .update(providedToken)
    .digest("hex");
  const existingToken = await db.query.provisioningTokens.findFirst({
    where: eq(provisioningTokens.tokenHash, provisioningTokenHash),
  });

  if (existingToken?.usedAt) {
    logger.warn(
      { tokenHash: provisioningTokenHash.substring(0, 8) },
      "Provisioning token already used"
    );
    return c.json({ error: "Provisioning token already used" }, 403);
  }

  const { email, backendDomain } = await c.req.json();

  if (!email || !backendDomain) {
    return c.json({ error: "Email and backendDomain required" }, 400);
  }

  // Generate invitation token
  const inviteToken = crypto.randomBytes(32).toString("hex");
  const inviteTokenHash = crypto
    .createHash("sha256")
    .update(inviteToken)
    .digest("hex");
  const expiresAt = new Date(Date.now() + 24 * 60 * 60 * 1000); // 24h
  await db.insert(adminInvitations).values({
    email,
    tokenHash: inviteTokenHash,
    expiresAt,
    backendDomain,
  });

  // Mark provisioning token as used (one-time use)
  if (existingToken) {
    await db
      .update(provisioningTokens)
      .set({ usedAt: new Date() })
      .where(eq(provisioningTokens.id, existingToken.id));
  } else {
    // First use - create record to track usage
    await db.insert(provisioningTokens).values({
      tokenHash: provisioningTokenHash,
      usedAt: new Date(),
    });
  }

  logger.info(
    { email, backendDomain },
    "Created admin invitation and invalidated provisioning token"
  );

  return c.json({
    token: inviteToken, // Return token to control plane (for email)
    expiresAt: expiresAt.toISOString(),
  });
});
