/**
 * The label a COMPOSITE proposal deserves, derived from the operations it will
 * actually apply.
 *
 * ── Why this exists ────────────────────────────────────────────────────────
 * A capture or import files ONE proposal carrying an `operations[]` plan — two
 * entity creates and a relation, say. `buildProposalSummary` looked for a
 * top-level `data.profileSlug` / `data.targetName` to name the thing, and a
 * composite has neither: `capture-propose.ts:312` documents that hoisting
 * `profileSlug` to the top level would hard-deny the whole proposal via the
 * create-profile guardrail. So the summary fell through to the generic base
 * kind, which the vocabulary door correctly suppresses, and the reviewer was
 * shown the bare verb — "Create" — for a write that creates a named note.
 *
 * Three such rows sat pending on the founder's pod for up to five days. You
 * cannot approve what you cannot read, and relay — now the primary surface —
 * is where approving happens.
 *
 * ── Why `operations[]` and not `reasoning` ─────────────────────────────────
 * `reasoning` is free text the author supplies to explain WHY they filed it.
 * On one of those three rows it read "Dogfood probe 2026-09-07: verifying the
 * revise door…" — promoting that would have rendered an author's note as the
 * proposal's title: worse than the generic verb, because it looks like a real
 * summary while describing intent instead of effect.
 *
 * `operations[]` is the PLAN THE EXECUTOR APPLIES. Deriving the label from it
 * is the property the approval prior-art demands ("preview generated by the
 * EXECUTION engine, not narrated" — Terraform `plan`): the preview and the
 * apply read the same artifact, so they cannot diverge.
 *
 * ── Pure, and in its own module, deliberately ──────────────────────────────
 * Imports NOTHING. `permission-check.ts` reaches config, a database and half
 * the router graph; a helper living inside it could not be loaded by a test in
 * a bare environment. That exact trap has cost this repo three times, most
 * recently on `proposal-class.test.ts` — one import turned a DB-free test into
 * one that could not even collect.
 */

/** The subset of a composite operation this reads. Additive fields ignored. */
export interface CompositeOperationLike {
  op?: unknown;
  profileSlug?: unknown;
  title?: unknown;
}

export interface CompositeLabel {
  /** The concrete kind of the first NAMED thing the plan creates. */
  objectKind: string;
  /** Its title, when it has a usable one. */
  objectName?: string;
  /** How many further operations the plan carries beyond that one. */
  extraCount: number;
}

function usableString(v: unknown): string | undefined {
  return typeof v === "string" && v.trim() ? v : undefined;
}

/**
 * Read a label out of a composite plan, or `null` when there is nothing
 * honest to say.
 *
 * `null` is a real answer and the caller must keep its existing behaviour on
 * it — a plan of pure relation ops names no object, and inventing one would be
 * worse than the generic verb.
 */
export function labelFromOperations(
  operations: unknown
): CompositeLabel | null {
  if (!Array.isArray(operations) || operations.length === 0) return null;

  // The first operation that names a KIND. A `create_relation` carries no
  // profileSlug, so a plan that only links existing things yields null and the
  // caller falls back — correctly, since the plan creates no named object.
  const named = operations.find(
    (o): o is CompositeOperationLike =>
      !!o &&
      typeof o === "object" &&
      usableString((o as CompositeOperationLike).profileSlug) !== undefined
  );
  if (!named) return null;

  const objectKind = usableString(named.profileSlug);
  if (!objectKind) return null;

  return {
    objectKind,
    objectName: usableString(named.title),
    // Everything the plan does BEYOND the one operation we named. Disclosed
    // rather than hidden: a reviewer told "Create Note X" about a plan that
    // also creates a person and a link has been told a true thing and a
    // misleading one.
    extraCount: operations.length - 1,
  };
}

/**
 * Append the honest remainder to a composed title.
 *
 * Product copy, not domain vocabulary — the vocabulary door owns the verb and
 * the noun, and `.claude/rules/vocabulary.md` explicitly leaves sentences and
 * counts local. "more" is plural-stable, so no pluralization rule is needed.
 */
export function withRemainder(title: string, extraCount: number): string {
  return extraCount > 0 ? `${title} + ${extraCount} more` : title;
}
