/**
 * Infinite Chat Router - tRPC routes for infinite chat with branching
 *
 * Handles:
 * - Thread management (chat_threads table)
 * - Message sending/receiving with Intelligence Hub
 * - Entity extraction
 * - Branching logic
 */

import { z } from "zod";
import { router, protectedProcedure, workspaceProcedure } from "../trpc.js";
import { TRPCError } from "@trpc/server";
import { db, eq, desc, and, or, lt, inArray } from "@synap/database";
import {
  chatThreads,
  conversationMessages,
  threadEntities,
  threadDocuments,
  ChatThreadType,
  ChatThreadStatus,
  ChatThreadAgentType,
  ThreadEntityRelationshipType,
  ThreadDocumentRelationshipType,
  proposals,
  ProposalStatus,
} from "@synap/database/schema";
import { resolveIntelligenceService } from "../utils/intelligence-routing.js";
import { emitChatEvent } from "../utils/chat-realtime-broadcast.js";
import { MessageLinksRepository } from "@synap/database";
import {
  MessageLinkTargetType,
  MessageLinkRelationshipType,
} from "@synap-core/types";
import { randomUUID } from "crypto";
import { createHash } from "crypto";
import type { AIStep, HubResponse, ProposedAction } from "@synap-core/types";
import type { ChatThread } from "@synap/database/schema";

/**
 * Infinite Chat Router (Week 2 implementation)
 *
 * Uses insertChatThreadSchema from database for true SSOT.
 */
export const infiniteChatRouter = router({
  /**
   * Create a new chat thread - Uses event sourcing for branch operations
   * Now includes context inheritance for branches via event-sourced executor
   */
  createThread: workspaceProcedure
    .input(
      z.object({
        parentThreadId: z.string().uuid().optional(),
        branchPurpose: z.string().optional(),
        agentId: z.string().optional(),
        agentType: z
          .enum([
            "meta",
            "default",
            "prompting",
            "knowledge-search",
            "code",
            "writing",
            "action",
          ])
          .optional(),
        agentConfig: z.record(z.string(), z.any()).optional(),
        inheritContext: z.boolean().default(true), // NEW: Inherit parent context
      })
    )
    .mutation(async ({ input, ctx }) => {
      // Get workspaceId from context (guaranteed by workspaceProcedure)
      const workspaceId = ctx.workspaceId;

      // If branching, verify parent thread is in same workspace
      if (input.parentThreadId) {
        const parentThread = await db.query.chatThreads.findFirst({
          where: eq(chatThreads.id, input.parentThreadId),
        });

        if (!parentThread) {
          throw new TRPCError({
            code: "NOT_FOUND",
            message: "Parent thread not found",
          });
        }

        // Verify parent thread is in same workspace (if chat threads had workspaceId)
        // For now, just use context workspaceId
      }

      // If this is a branch, use event sourcing
      if (input.parentThreadId) {
        const { emitRequestEvent } = await import("../utils/emit-event.js");

        await emitRequestEvent({
          subjectType: "chatThread",
          action: "branch",
          subjectId: input.parentThreadId,
          data: {
            userId: ctx.userId,
            // Projects: Removed projectId (use relations table if needed)
            parentThreadId: input.parentThreadId,
            branchPurpose: input.branchPurpose,
            agentId: input.agentId,
            agentType: input.agentType,
            agentConfig: input.agentConfig,
            inheritContext: input.inheritContext,
          },
          userId: ctx.userId,
          workspaceId,
        });

        // Return immediately, executor will process async
        return {
          threadId: undefined, // Will be generated by executor
          status: "requested",
          message: "Branch creation requested",
        };
      }

      // For main threads, create directly (no event sourcing needed)
      const [thread] = await db
        .insert(chatThreads)
        .values({
          userId: ctx.userId,
          workspaceId: workspaceId ?? null,
          threadType: ChatThreadType.MAIN,
          status: ChatThreadStatus.ACTIVE,
          agentId: input.agentId || "orchestrator", // Explicitly provide agentId (required, has default in schema)
          agentType: input.agentType
            ? (input.agentType as ChatThreadAgentType)
            : ChatThreadAgentType.DEFAULT, // Explicitly provide agentType (required, has default in schema)
        })
        .returning();

      const threadId = thread.id;

      // Emit real-time events via Realtime bridge
      emitChatEvent({
        event: "thread:created",
        data: { threadId, userId: ctx.userId },
        workspaceId: workspaceId ?? null,
        userId: ctx.userId,
      });

      return { threadId, thread };
    }),

  /**
   * Create a document comment: new thread with one user message linked to the document at the given selection.
   * No AI response. Used when user selects text and clicks "Add comment" in the editor.
   */
  createDocumentComment: workspaceProcedure
    .input(
      z.object({
        documentId: z.string().uuid(),
        position: z.object({
          start: z.number().int().nonnegative(),
          end: z.number().int().nonnegative(),
        }),
        content: z.string().min(1),
      })
    )
    .mutation(async ({ input, ctx }) => {
      const workspaceId = ctx.workspaceId;
      if (!workspaceId) {
        throw new TRPCError({
          code: "BAD_REQUEST",
          message: "Workspace context required",
        });
      }

      const threadId = randomUUID();
      const userMessageId = randomUUID();
      const userMessageHash = createHash("sha256")
        .update(`${userMessageId}${input.content}`)
        .digest("hex");

      await db.insert(chatThreads).values({
        id: threadId,
        userId: ctx.userId,
        workspaceId,
        threadType: ChatThreadType.MAIN,
        status: ChatThreadStatus.ACTIVE,
        agentId: "orchestrator",
        agentType: ChatThreadAgentType.DEFAULT,
      });

      await db.insert(conversationMessages).values({
        id: userMessageId,
        threadId,
        role: "user",
        content: input.content,
        userId: ctx.userId,
        previousHash: "",
        hash: userMessageHash,
      });

      const linksRepo = new MessageLinksRepository(db);
      await linksRepo.create({
        messageId: userMessageId,
        targetType: MessageLinkTargetType.DOCUMENT,
        targetId: input.documentId,
        relationshipType: MessageLinkRelationshipType.COMMENTS,
        position: input.position,
        userId: ctx.userId,
        workspaceId,
      });

      emitChatEvent({
        event: "thread:created",
        data: { threadId, userId: ctx.userId },
        workspaceId,
        userId: ctx.userId,
      });

      return { threadId, messageId: userMessageId };
    }),

  /**
   * Send message to Intelligence Hub and get AI response (with streaming).
   * When threadId is omitted, the backend creates a new thread and attaches the message (e.g. for command-palette "Ask AI" or first message).
   */
  sendMessage: protectedProcedure
    .input(
      z.object({
        /** When omitted, backend creates a new thread and returns its id in the response. */
        threadId: z.string().uuid().optional(),
        content: z.string().min(1),
        /** Required when threadId is omitted; otherwise used for entity create/update – event chain. */
        workspaceId: z.string().uuid().optional(),
      })
    )
    .mutation(async ({ input, ctx }) => {
      let threadId = input.threadId;
      const content = input.content;
      const workspaceId = input.workspaceId ?? ctx.workspaceId ?? undefined;

      // Create thread when not provided (single entry point: "send message" from anywhere)
      if (!threadId) {
        if (!workspaceId) {
          throw new TRPCError({
            code: "BAD_REQUEST",
            message:
              "workspaceId is required when sending a message without a thread",
          });
        }
        const [thread] = await db
          .insert(chatThreads)
          .values({
            userId: ctx.userId,
            workspaceId: workspaceId ?? null,
            threadType: ChatThreadType.MAIN,
            status: ChatThreadStatus.ACTIVE,
            agentId: "orchestrator",
            agentType: ChatThreadAgentType.DEFAULT,
          })
          .returning();
        threadId = thread.id;
        emitChatEvent({
          event: "thread:created",
          data: { threadId, userId: ctx.userId },
          workspaceId: workspaceId ?? null,
          userId: ctx.userId,
        });
      }

      // Get thread
      const thread = await db.query.chatThreads.findFirst({
        where: eq(chatThreads.id, threadId),
      });

      if (!thread) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Thread not found",
        });
      }

      // Save user message
      const userMessageId = randomUUID();
      const userMessageHash = createHash("sha256")
        .update(`${userMessageId}${content}`)
        .digest("hex");

      await db.insert(conversationMessages).values({
        id: userMessageId,
        threadId,
        role: "user",
        content,
        userId: ctx.userId,
        previousHash: "",
        hash: userMessageHash,
      });

      // Resolve intelligence service dynamically
      const resolvedService = await resolveIntelligenceService({
        userId: ctx.userId,
        workspaceId: ctx.workspaceId || undefined, // Use workspaceId from context if available
        capability: "chat",
      });

      // Stream from Intelligence Service (now dynamic)
      let fullContent = "";
      const aiSteps: AIStep[] = [];
      const proposedActions: ProposedAction[] = [];
      let hubResponse: Partial<HubResponse> = { content: "" };

      try {
        const stream = resolvedService.client.sendMessageStream({
          query: content,
          threadId,
          userId: ctx.userId,
          agentId: thread.agentId ?? "orchestrator",
          agentType: thread.agentType ?? "meta",
          workspaceId,
        });

        for await (const chunk of stream) {
          if (chunk.type === "chunk" && chunk.content) {
            fullContent += chunk.content;

            emitChatEvent({
              event: "chat:stream",
              data: {
                threadId,
                type: "chunk",
                content: chunk.content,
                isComplete: false,
              },
              workspaceId: workspaceId ?? null,
              userId: ctx.userId,
            });
          } else if (chunk.type === "step" && chunk.step) {
            aiSteps.push(chunk.step);

            emitChatEvent({
              event: "ai:step",
              data: {
                threadId,
                messageId: userMessageId,
                step: chunk.step,
              },
              workspaceId: workspaceId ?? null,
              userId: ctx.userId,
            });
          } else if (chunk.type === "proposal" && chunk.proposal) {
            proposedActions.push(chunk.proposal);
            emitChatEvent({
              event: "ai:proposal",
              data: {
                threadId,
                messageId: userMessageId,
                proposal: chunk.proposal,
              },
              workspaceId: workspaceId ?? null,
              userId: ctx.userId,
            });
          } else if (chunk.type === "entities" && chunk.entities) {
            hubResponse.entities = chunk.entities;
          } else if (chunk.type === "branch_decision" && chunk.decision) {
            hubResponse.branchDecision = chunk.decision;
          } else if (chunk.type === "complete") {
            if (chunk.data) {
              const data = chunk.data as Partial<HubResponse>;
              hubResponse = { ...hubResponse, ...data };
              if (data.proposedActions?.length) {
                proposedActions.push(...data.proposedActions);
              }
            }
            hubResponse.proposedActions =
              proposedActions.length > 0 ? proposedActions : undefined;

            emitChatEvent({
              event: "chat:stream",
              data: { threadId, type: "complete", isComplete: true },
              workspaceId: workspaceId ?? null,
              userId: ctx.userId,
            });
          }
        }
      } catch (streamError) {
        console.error(
          "Streaming error, falling back to non-streaming:",
          streamError
        );

        // ✅ ADDED: Notify frontend of streaming failure (Issue #9)
        emitChatEvent({
          event: "chat:stream:error",
          data: {
            threadId,
            error:
              streamError instanceof Error
                ? streamError.message
                : "Streaming failed",
            fallback: true,
          },
          workspaceId: workspaceId ?? null,
          userId: ctx.userId,
        });

        // Fallback to non-streaming using the same resolved service
        hubResponse = await resolvedService.client.sendMessage({
          query: content,
          threadId,
          userId: ctx.userId,
          agentId: thread.agentId ?? "orchestrator",
          agentType: thread.agentType ?? "meta",
          workspaceId,
        });

        fullContent = hubResponse.content || "";
      }

      // Create proposal rows for each stream proposedAction so approve/reject use the same table
      const finalProposedActions = hubResponse?.proposedActions ?? [];
      const proposalIds: string[] = [];
      const resolvedWorkspaceId = workspaceId ?? ctx.workspaceId ?? null;

      if (finalProposedActions.length > 0 && resolvedWorkspaceId) {
        const { documents, entities } = await import("@synap/database/schema");

        for (const action of finalProposedActions) {
          try {
            if (action.toolName === "update_document") {
              const documentId = action.args?.documentId as string | undefined;
              const proposedContent = action.args?.content as
                | string
                | undefined;
              if (!documentId || typeof proposedContent !== "string") continue;

              const doc = await db.query.documents.findFirst({
                where: eq(documents.id, documentId),
              });
              if (!doc) continue;

              const entity = await db.query.entities.findFirst({
                where: eq(entities.documentId, documentId),
              });
              const docWorkspaceId = entity?.workspaceId ?? resolvedWorkspaceId;
              const originalContent = action.args?.originalContent as
                | string
                | undefined;
              const expiresAt = new Date();
              expiresAt.setDate(expiresAt.getDate() + 7);

              const [proposal] = await db
                .insert(proposals)
                .values({
                  workspaceId: docWorkspaceId,
                  targetType: "document",
                  targetId: documentId,
                  proposalType: "ai_edit",
                  data: {
                    proposedBy: "ai",
                    changes: [
                      {
                        op: "replace",
                        range: [0, (originalContent ?? "").length],
                        text: proposedContent,
                      },
                    ],
                    originalContent: originalContent ?? null,
                    proposedContent,
                    expiresAt: expiresAt.toISOString(),
                    messageId: undefined,
                    threadId,
                  },
                  status: ProposalStatus.PENDING,
                })
                .returning();

              if (proposal?.id) proposalIds.push(proposal.id);
            } else if (
              action.toolName === "create_entity" ||
              action.toolName === "update_entity"
            ) {
              const targetId =
                (action.args?.entityId as string | undefined) ??
                `pending-${action.id}`;
              const changeType =
                action.toolName === "create_entity" ? "create" : "update";

              const [proposal] = await db
                .insert(proposals)
                .values({
                  workspaceId: resolvedWorkspaceId,
                  targetType: "entity",
                  targetId,
                  proposalType: changeType,
                  data: {
                    ...action,
                    targetType: "entity",
                    changeType,
                    requestId: action.id,
                    messageId: undefined,
                    threadId,
                    data: action.args,
                  },
                  status: ProposalStatus.PENDING,
                })
                .returning();

              if (proposal?.id) proposalIds.push(proposal.id);
            }
          } catch (err) {
            console.error(
              "[infinite-chat] Failed to create proposal row for action:",
              action.id,
              action.toolName,
              err
            );
          }
        }
      }

      // Save assistant message
      const assistantMessageId = randomUUID();
      const assistantMessageHash = createHash("sha256")
        .update(`${assistantMessageId}${fullContent}${userMessageHash}`)
        .digest("hex");

      const messageMetadata = {
        aiSteps: aiSteps.length > 0 ? aiSteps : hubResponse?.aiSteps || [],
        tokens: hubResponse?.usage?.totalTokens,
        proposedActions:
          proposedActions.length > 0 ? proposedActions : undefined,
        proposalIds: proposalIds.length > 0 ? proposalIds : undefined,
      };

      await db.insert(conversationMessages).values({
        id: assistantMessageId,
        threadId,
        role: "assistant",
        content: fullContent,
        userId: ctx.userId,
        previousHash: userMessageHash,
        hash: assistantMessageHash,
        metadata: messageMetadata as any,
      });

      // Create entities via event chain for consistency
      const createdEntities = [];
      const entities = hubResponse?.entities || [];

      if (entities.length > 0) {
        const { inngest } = await import("@synap/jobs");

        for (const entity of entities) {
          // ✅ Publish .requested event
          await inngest.send({
            name: "entity.create.requested",
            data: {
              type: entity.type,
              title: entity.title,
              preview: entity.description,
              userId: ctx.userId,
              source: "chat-extraction",
            },
            user: { id: ctx.userId },
          });

          createdEntities.push({
            type: entity.type,
            title: entity.title,
            status: "requested",
          });

          // Link entity to thread once it's created (will be done by worker)
          // For now, we'll link it when the entity is actually created
          // This will be handled by the entity creation worker
        }
      }

      emitChatEvent({
        event: "chat:message",
        data: {
          threadId,
          message: {
            id: assistantMessageId,
            threadId,
            role: "assistant",
            content: fullContent,
            userId: ctx.userId,
            timestamp: new Date(),
            previousHash: userMessageHash,
            hash: assistantMessageHash,
            metadata: messageMetadata,
          },
          userId: ctx.userId,
        },
        workspaceId: workspaceId ?? null,
        userId: ctx.userId,
      });

      // Create branch if decided
      let branchThread = undefined;
      const branchDecision = hubResponse?.branchDecision;
      if (branchDecision?.shouldBranch) {
        const [branch] = await db
          .insert(chatThreads)
          .values({
            userId: ctx.userId,
            // Projects: Removed projectIds (use relations table if needed)
            parentThreadId: threadId,
            branchedFromMessageId: assistantMessageId,
            branchPurpose:
              branchDecision.suggestedPurpose || branchDecision.reason,
            agentId: branchDecision.suggestedAgentType || "research-agent",
            threadType: ChatThreadType.BRANCH,
            status: ChatThreadStatus.ACTIVE,
          })
          .returning();

        branchThread = branch;
      }

      await db
        .update(chatThreads)
        .set({ updatedAt: new Date() })
        .where(eq(chatThreads.id, threadId));

      return {
        threadId,
        messageId: assistantMessageId,
        content: fullContent,
        entities: createdEntities,
        branchDecision,
        branchThread,
        aiSteps,
      };
    }),

  /**
   * Get messages for a thread (with cursor pagination)
   */
  getMessages: protectedProcedure
    .input(
      z.object({
        threadId: z.string().uuid(),
        cursor: z.string().uuid().optional(), // Message ID for pagination
        limit: z.number().min(1).max(100).default(50),
      })
    )
    .query(async ({ input, ctx }) => {
      const thread = await db.query.chatThreads.findFirst({
        where: eq(chatThreads.id, input.threadId),
      });
      if (!thread) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Thread not found",
        });
      }
      if (thread.userId !== ctx.userId) {
        throw new TRPCError({
          code: "FORBIDDEN",
          message: "Access denied to this thread",
        });
      }
      if (
        ctx.workspaceId &&
        thread.workspaceId &&
        thread.workspaceId !== ctx.workspaceId
      ) {
        throw new TRPCError({
          code: "FORBIDDEN",
          message: "Thread is not in the current workspace",
        });
      }

      const messages = await db.query.conversationMessages.findMany({
        where: and(
          eq(conversationMessages.threadId, input.threadId),
          input.cursor
            ? lt(conversationMessages.id, input.cursor) // Cursor-based pagination
            : undefined
        ),
        orderBy: [desc(conversationMessages.timestamp)],
        limit: input.limit + 1, // Fetch one extra to check if there's more
      });

      const hasMore = messages.length > input.limit;
      const nextCursor = hasMore ? messages[input.limit - 1].id : undefined;

      return {
        messages: hasMore ? messages.slice(0, -1) : messages,
        nextCursor,
        hasMore,
      };
    }),

  /**
   * List threads (optionally filtered by workspace)
   */
  listThreads: protectedProcedure
    .input(
      z.object({
        /** When provided, only threads in this workspace are returned. Omit for legacy: all user threads. */
        workspaceId: z.string().uuid().optional(),
        threadType: z.enum(["main", "branch"]).optional(),
        limit: z.number().min(1).max(100).default(20),
      })
    )
    .query(async ({ input, ctx }) => {
      const conditions: any[] = [eq(chatThreads.userId, ctx.userId)];

      if (input.workspaceId !== undefined) {
        conditions.push(eq(chatThreads.workspaceId, input.workspaceId));
      }

      if (input.threadType) {
        conditions.push(
          eq(
            chatThreads.threadType,
            input.threadType === "main"
              ? ChatThreadType.MAIN
              : ChatThreadType.BRANCH
          )
        );
      }

      const threads = await db.query.chatThreads.findMany({
        where: and(...conditions),
        orderBy: [desc(chatThreads.updatedAt)],
        limit: input.limit,
      });

      return { threads };
    }),

  /**
   * Get branches for a thread
   */
  getBranches: protectedProcedure
    .input(
      z.object({
        parentThreadId: z.string().uuid(),
      })
    )
    .query(async ({ input }) => {
      const branches = await db.query.chatThreads.findMany({
        where: eq(chatThreads.parentThreadId, input.parentThreadId),
        orderBy: [desc(chatThreads.createdAt)],
      });

      return { branches };
    }),

  /**
   * Merge branch - Uses event sourcing
   */
  mergeBranch: protectedProcedure
    .input(
      z.object({
        branchId: z.string().uuid(),
        summary: z.string().optional(),
      })
    )
    .mutation(async ({ input, ctx }) => {
      const branch = await db.query.chatThreads.findFirst({
        where: eq(chatThreads.id, input.branchId),
      });

      if (!branch || branch.threadType !== "branch") {
        throw new Error("Branch not found");
      }

      if (!branch.parentThreadId) {
        throw new Error("Branch has no parent thread");
      }

      // Use event sourcing
      const { emitRequestEvent } = await import("../utils/emit-event.js");

      await emitRequestEvent({
        subjectType: "chatThread",
        action: "merge",
        subjectId: input.branchId,
        data: {
          branchId: input.branchId,
          parentThreadId: branch.parentThreadId,
          summary: input.summary,
          userId: ctx.userId,
        },
        userId: ctx.userId,
        workspaceId: ctx.workspaceId || undefined, // Use workspaceId from context if available
      });

      // Return immediately, executor will process async
      return {
        status: "requested",
        message: "Branch merge requested",
      };
    }),

  /**
   * Get single thread with optional context and branches
   */
  getThread: protectedProcedure
    .input(
      z.object({
        threadId: z.string().uuid(),
        includeContext: z.boolean().default(true), // Include entities/documents
        includeBranches: z.boolean().default(false), // Include branch tree
      })
    )
    .query(async ({ input, ctx }) => {
      // Get thread
      const thread = await db.query.chatThreads.findFirst({
        where: and(
          eq(chatThreads.id, input.threadId),
          eq(chatThreads.userId, ctx.userId)
        ),
      });

      if (!thread) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Thread not found",
        });
      }
      if (
        ctx.workspaceId &&
        thread.workspaceId &&
        thread.workspaceId !== ctx.workspaceId
      ) {
        throw new TRPCError({
          code: "FORBIDDEN",
          message: "Thread is not in the current workspace",
        });
      }

      // Get context (entities/documents) if requested
      let entities: (typeof threadEntities.$inferSelect)[] = [];
      let documents: (typeof threadDocuments.$inferSelect)[] = [];

      if (input.includeContext) {
        entities = await db.query.threadEntities.findMany({
          where: eq(threadEntities.threadId, input.threadId),
        });

        documents = await db.query.threadDocuments.findMany({
          where: eq(threadDocuments.threadId, input.threadId),
        });
      }

      // Get branch tree if requested
      let branchTree: any = null;
      if (input.includeBranches) {
        const allBranches = await db.query.chatThreads.findMany({
          where: or(
            eq(chatThreads.id, input.threadId),
            eq(chatThreads.parentThreadId, input.threadId)
          ),
        });

        // Build tree structure
        branchTree = buildBranchTree(allBranches, input.threadId);
      }

      return {
        thread,
        entities: input.includeContext ? entities : undefined,
        documents: input.includeContext ? documents : undefined,
        branchTree: input.includeBranches ? branchTree : undefined,
      };
    }),

  /**
   * Update thread metadata
   */
  updateThread: protectedProcedure
    .input(
      z.object({
        threadId: z.string().uuid(),
        title: z.string().optional(),
        agentId: z.string().optional(),
        agentType: z
          .enum([
            "meta",
            "default",
            "prompting",
            "knowledge-search",
            "code",
            "writing",
            "action",
          ])
          .optional(),
        agentConfig: z.record(z.string(), z.unknown()).optional(),
      })
    )
    .mutation(async ({ input, ctx }) => {
      // Verify thread exists and user owns it
      const thread = await db.query.chatThreads.findFirst({
        where: and(
          eq(chatThreads.id, input.threadId),
          eq(chatThreads.userId, ctx.userId)
        ),
      });

      if (!thread) {
        throw new Error("Thread not found");
      }

      // Update thread directly (simple operation, no event sourcing needed)
      await db
        .update(chatThreads)
        .set({
          title: input.title,
          agentId: input.agentId,
          agentType: input.agentType
            ? (input.agentType as ChatThreadAgentType)
            : undefined,
          agentConfig: input.agentConfig,
          updatedAt: new Date(),
        })
        .where(eq(chatThreads.id, input.threadId));

      emitChatEvent({
        event: "thread:updated",
        data: { threadId: input.threadId, userId: ctx.userId },
        workspaceId: thread.workspaceId ?? ctx.workspaceId ?? null,
        userId: ctx.userId,
      });

      return {
        status: "updated",
        threadId: input.threadId,
      };
    }),

  /**
   * Archive thread (soft delete)
   */
  archiveThread: protectedProcedure
    .input(
      z.object({
        threadId: z.string().uuid(),
      })
    )
    .mutation(async ({ input, ctx }) => {
      // Verify thread exists and user owns it
      const thread = await db.query.chatThreads.findFirst({
        where: and(
          eq(chatThreads.id, input.threadId),
          eq(chatThreads.userId, ctx.userId)
        ),
      });

      if (!thread) {
        throw new Error("Thread not found");
      }

      // Update status to archived
      await db
        .update(chatThreads)
        .set({
          status: ChatThreadStatus.ARCHIVED,
          updatedAt: new Date(),
        })
        .where(eq(chatThreads.id, input.threadId));

      emitChatEvent({
        event: "thread:archived",
        data: { threadId: input.threadId, userId: ctx.userId },
        workspaceId: thread.workspaceId ?? ctx.workspaceId ?? null,
        userId: ctx.userId,
      });

      return {
        status: "archived",
        threadId: input.threadId,
      };
    }),

  /**
   * Get branch tree structure (not flat list)
   */
  getBranchTree: protectedProcedure
    .input(
      z.object({
        rootThreadId: z.string().uuid(),
      })
    )
    .query(async ({ input, ctx }) => {
      // Get all threads in the tree (root + all descendants)
      const allThreads = await db.query.chatThreads.findMany({
        where: and(
          or(
            eq(chatThreads.id, input.rootThreadId),
            eq(chatThreads.parentThreadId, input.rootThreadId)
          ),
          eq(chatThreads.userId, ctx.userId)
        ),
      });

      // Build tree structure
      const tree = buildBranchTree(allThreads, input.rootThreadId);

      // Categorize branches
      const activeBranches = allThreads.filter(
        (t) => t.status === "active" && t.threadType === "branch"
      );
      const mergedBranches = allThreads.filter(
        (t) => t.status === "merged" && t.threadType === "branch"
      );

      return {
        tree,
        flatBranches: allThreads.filter((t) => t.threadType === "branch"),
        activeBranches,
        mergedBranches,
      };
    }),

  /**
   * Get thread context (entities and documents)
   */
  getThreadContext: protectedProcedure
    .input(
      z.object({
        threadId: z.string().uuid(),
        relationshipTypes: z
          .array(
            z.enum([
              "used_as_context",
              "created",
              "updated",
              "referenced",
              "inherited_from_parent",
            ])
          )
          .optional(),
      })
    )
    .query(async ({ input, ctx }) => {
      // Verify thread exists and user owns it
      const thread = await db.query.chatThreads.findFirst({
        where: and(
          eq(chatThreads.id, input.threadId),
          eq(chatThreads.userId, ctx.userId)
        ),
      });

      if (!thread) {
        throw new Error("Thread not found");
      }

      // Map string array to enum array
      const relationshipTypeEnums = input.relationshipTypes
        ? input.relationshipTypes.map(
            (rt) =>
              ThreadEntityRelationshipType[
                rt.toUpperCase() as keyof typeof ThreadEntityRelationshipType
              ]
          )
        : undefined;

      const documentRelationshipTypeEnums = input.relationshipTypes
        ? input.relationshipTypes.map(
            (rt) =>
              ThreadDocumentRelationshipType[
                rt.toUpperCase() as keyof typeof ThreadDocumentRelationshipType
              ]
          )
        : undefined;

      // Build where clause
      const whereClause = and(
        eq(threadEntities.threadId, input.threadId),
        relationshipTypeEnums
          ? inArray(threadEntities.relationshipType, relationshipTypeEnums)
          : undefined
      );

      // Get entities
      const entities = await db.query.threadEntities.findMany({
        where: whereClause,
      });

      // Get documents
      const documents = await db.query.threadDocuments.findMany({
        where: and(
          eq(threadDocuments.threadId, input.threadId),
          documentRelationshipTypeEnums
            ? inArray(
                threadDocuments.relationshipType,
                documentRelationshipTypeEnums
              )
            : undefined
        ),
      });

      return {
        entities,
        documents,
      };
    }),
});

/**
 * Helper function to build branch tree structure
 */
function buildBranchTree(
  threads: ChatThread[],
  rootId: string
): { thread: ChatThread; children: any[] } | null {
  const root = threads.find((t) => t.id === rootId);
  if (!root) return null;

  const children = threads
    .filter((t) => t.parentThreadId === rootId)
    .map((child) => buildBranchTree(threads, child.id))
    .filter(Boolean) as any[];

  return {
    thread: root,
    children,
  };
}
