-- Migration: Provisioning Tokens
-- Description: Table for storing one-time provisioning tokens (control plane flow)
-- These tokens are generated by the control plane and passed to the backend during installation.
-- They can be used ONCE to create the first admin invitation, then are invalidated.
-- Self-hosted backends don't have provisioning tokens, so the control plane cannot call them.

CREATE TABLE IF NOT EXISTS "provisioning_tokens" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "token_hash" text NOT NULL UNIQUE,
  "used_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_provisioning_tokens_token_hash" ON "provisioning_tokens"("token_hash");
