#!/bin/bash
# Setup local development environment
# Auto-generates secrets, prompts for needed values, uses existing .env if present
# Similar to install.sh but for local development

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$ROOT_DIR"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

ENV_FILE=".env.development.local"

echo -e "${BLUE}🔧 Setting up local development environment...${NC}"
echo ""

# Function to generate random secret (32 chars, like install.sh)
generate_secret() {
    openssl rand -base64 32 | tr -d "=+/" | cut -c1-32
}

# Function to generate 64-char secret (for JWT)
generate_secret_64() {
    openssl rand -base64 64 | tr -d "=+/" | cut -c1-64
}

# Function to load existing value from .env file (safe, no code execution)
load_env_var() {
    local var_name=$1
    local default_value=$2
    
    if [ -f "$ENV_FILE" ]; then
        local value=$(grep "^${var_name}=" "$ENV_FILE" 2>/dev/null | cut -d'=' -f2- | sed 's/^"//;s/"$//' | sed "s/^'//;s/'$//" | xargs || echo "")
        if [ -n "$value" ]; then
            echo "$value"
            return
        fi
    fi
    
    echo "$default_value"
}

# Function to get secret: use existing or generate new
get_secret() {
    local key=$1
    local existing=$(load_env_var "$key" "")
    
    if [ -n "$existing" ]; then
        echo "$existing"
    else
        generate_secret
    fi
}

# Function to get secret (64 chars)
get_secret_64() {
    local key=$1
    local existing=$(load_env_var "$key" "")
    
    if [ -n "$existing" ]; then
        echo "$existing"
    else
        generate_secret_64
    fi
}

# Function to read or prompt (with existing value as default)
# Note: This function outputs to stderr (prompts) and stdout (value)
read_or_prompt() {
    local key=$1
    local prompt=$2
    local default=$3
    local is_secret=${4:-false}
    
    # Check if value exists in .env file
    local existing=$(load_env_var "$key" "")
    if [ -n "$existing" ]; then
        default="$existing"
    fi
    
    # If default is empty and we have a generated default, use it
    if [ -z "$default" ] && [ -n "$4" ] && [ "$4" = "generate" ]; then
        default=$(generate_secret)
    fi
    
    # Prompt for value (to stderr so it doesn't get captured)
    if [ -n "$default" ]; then
        echo -ne "${YELLOW}${prompt}${NC} [${default}]: " >&2
    else
        echo -ne "${YELLOW}${prompt}${NC}: " >&2
    fi
    
    if [ "$is_secret" = "true" ]; then
        read -s value
        echo "" >&2
    else
        read value
    fi
    
    if [ -z "$value" ] && [ -n "$default" ]; then
        value="$default"
    fi
    
    # Output value to stdout (for capture)
    echo "$value"
}

# Check if .env.development.local already exists
if [ -f "$ENV_FILE" ]; then
    echo -e "${GREEN}✅ ${ENV_FILE} already exists${NC}"
    echo -e "${YELLOW}ℹ️  Using existing values from ${ENV_FILE}${NC}"
    echo -e "${YELLOW}ℹ️  Secrets will be preserved, missing values will be auto-generated${NC}"
    echo ""
    read -p "Update/regenerate? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo -e "${GREEN}✅ Using existing ${ENV_FILE} (no changes)${NC}"
        echo ""
        echo -e "${BLUE}📝 To start development:${NC}"
        echo "1. Start local services: ${GREEN}./scripts/dev-local.sh${NC}"
        echo "2. Run migrations: ${GREEN}pnpm db:migrate${NC}"
        echo "3. Start Inngest: ${GREEN}npx inngest-cli@latest dev${NC}"
        echo "4. Start API: ${GREEN}pnpm dev:local${NC}"
        exit 0
    fi
    echo -e "${BLUE}📝 Updating ${ENV_FILE} (preserving existing values)...${NC}"
else
    echo -e "${BLUE}📝 Creating ${ENV_FILE}...${NC}"
fi

# Start building .env file
cat > "$ENV_FILE" <<EOF
# ============================================================================
# LOCAL DEVELOPMENT ENVIRONMENT
# ============================================================================
# Generated by setup-dev-local.sh on $(date)
# This file is for local development with all services running locally
# ============================================================================

NODE_ENV=development
PORT=4000
LOG_LEVEL=debug

# ============================================================================
# DATABASE (Local PostgreSQL)
# ============================================================================
EOF

# Database password (use existing or default)
# Database password (use existing or default - no prompt needed for local dev)
DB_PASSWORD=$(load_env_var "POSTGRES_PASSWORD" "synap_dev_password")
echo "POSTGRES_PASSWORD=${DB_PASSWORD}" >> "$ENV_FILE"
echo "DATABASE_URL=postgresql://synap:${DB_PASSWORD}@localhost:5432/synap" >> "$ENV_FILE"
echo "" >> "$ENV_FILE"

# ============================================================================
# AUTHENTICATION (Local Kratos + Hydra)
# ============================================================================
cat >> "$ENV_FILE" <<EOF
# ============================================================================
# AUTHENTICATION (Local Kratos + Hydra)
# ============================================================================
KRATOS_PUBLIC_URL=http://localhost:4433
KRATOS_ADMIN_URL=http://localhost:4434
EOF

# Generate Kratos secrets (auto-generate if not existing)
KRATOS_COOKIE=$(get_secret "KRATOS_SECRETS_COOKIE")
KRATOS_CIPHER=$(get_secret "KRATOS_SECRETS_CIPHER")
KRATOS_WEBHOOK=$(get_secret "KRATOS_WEBHOOK_SECRET")

cat >> "$ENV_FILE" <<EOF
KRATOS_SECRETS_COOKIE=${KRATOS_COOKIE}
KRATOS_SECRETS_CIPHER=${KRATOS_CIPHER}
KRATOS_WEBHOOK_SECRET=${KRATOS_WEBHOOK}

HYDRA_PUBLIC_URL=http://localhost:4444
HYDRA_ADMIN_URL=http://localhost:4445
EOF

# Generate Hydra secret (auto-generate if not existing)
HYDRA_SECRET=$(get_secret "ORY_HYDRA_SECRETS_SYSTEM")
echo "ORY_HYDRA_SECRETS_SYSTEM=${HYDRA_SECRET}" >> "$ENV_FILE"
echo "" >> "$ENV_FILE"

# ============================================================================
# STORAGE (Local MinIO)
# ============================================================================
cat >> "$ENV_FILE" <<EOF
# ============================================================================
# STORAGE (Local MinIO)
# ============================================================================
STORAGE_PROVIDER=minio
MINIO_ENDPOINT=http://localhost:9000
EOF

# MinIO credentials (use existing or defaults)
MINIO_ACCESS=$(load_env_var "MINIO_ACCESS_KEY" "minioadmin")
MINIO_SECRET=$(load_env_var "MINIO_SECRET_KEY" "minioadmin")

cat >> "$ENV_FILE" <<EOF
MINIO_ACCESS_KEY=${MINIO_ACCESS}
MINIO_SECRET_KEY=${MINIO_SECRET}
MINIO_BUCKET=synap-storage
MINIO_USE_SSL=false
EOF
echo "" >> "$ENV_FILE"

# ============================================================================
# CACHE (Local Redis)
# ============================================================================
cat >> "$ENV_FILE" <<EOF
# ============================================================================
# CACHE (Local Redis)
# ============================================================================
REDIS_URL=redis://localhost:6379
EOF
echo "" >> "$ENV_FILE"

# ============================================================================
# SEARCH (Local Typesense)
# ============================================================================
cat >> "$ENV_FILE" <<EOF
# ============================================================================
# SEARCH (Local Typesense)
# ============================================================================
TYPESENSE_HOST=localhost
TYPESENSE_PORT=8108
TYPESENSE_PROTOCOL=http
EOF

# Typesense API key (auto-generate if not existing)
TYPESENSE_KEY=$(get_secret "TYPESENSE_API_KEY")
echo "TYPESENSE_API_KEY=${TYPESENSE_KEY}" >> "$ENV_FILE"
echo "TYPESENSE_ADMIN_API_KEY=${TYPESENSE_KEY}" >> "$ENV_FILE"
echo "" >> "$ENV_FILE"

# ============================================================================
# BACKGROUND JOBS (Local Inngest)
# ============================================================================
cat >> "$ENV_FILE" <<EOF
# ============================================================================
# BACKGROUND JOBS (Local Inngest)
# ============================================================================
# Start Inngest separately: npx inngest-cli@latest dev
INNGEST_DEV=true
INNGEST_BASE_URL=http://localhost:8288
EOF

# Inngest keys (auto-generate if not existing)
INNGEST_EVENT=$(get_secret "INNGEST_EVENT_KEY")
INNGEST_SIGNING=$(get_secret "INNGEST_SIGNING_KEY")

cat >> "$ENV_FILE" <<EOF
INNGEST_EVENT_KEY=${INNGEST_EVENT}
INNGEST_SIGNING_KEY=${INNGEST_SIGNING}
EOF
echo "" >> "$ENV_FILE"

# ============================================================================
# JWT & SECURITY
# ============================================================================
# JWT secret (64 chars, like install.sh)
JWT_SECRET=$(get_secret_64 "JWT_SECRET")
cat >> "$ENV_FILE" <<EOF
# ============================================================================
# JWT & SECURITY
# ============================================================================
JWT_SECRET=${JWT_SECRET}
EOF
echo "" >> "$ENV_FILE"

# ============================================================================
# AI PROVIDERS (Optional)
# ============================================================================
cat >> "$ENV_FILE" <<EOF
# ============================================================================
# AI PROVIDERS (Optional - for local testing)
# ============================================================================
# ANTHROPIC_API_KEY=your-anthropic-key
# OPENAI_API_KEY=your-openai-key
EOF
echo "" >> "$ENV_FILE"

# ============================================================================
# NOTES
# ============================================================================
cat >> "$ENV_FILE" <<EOF
# ============================================================================
# NOTES
# ============================================================================
# 1. Start local services: ./scripts/dev-local.sh
#    Or: docker compose -f docker-compose.local.yml up -d
# 2. Run migrations: pnpm db:migrate
# 3. Start Inngest: npx inngest-cli@latest dev
# 4. Start API: pnpm dev:local
EOF

echo ""
echo -e "${GREEN}✅ ${ENV_FILE} created/updated successfully!${NC}"
echo ""

# Show summary
echo -e "${BLUE}📊 Configuration Summary:${NC}"
echo "  • Database: PostgreSQL (localhost:5432)"
echo "  • Auth: Kratos + Hydra (localhost)"
echo "  • Storage: MinIO (localhost:9000)"
echo "  • Cache: Redis (localhost:6379)"
echo "  • Search: Typesense (localhost:8108)"
echo "  • Jobs: Inngest (localhost:8288)"
echo ""
echo -e "${YELLOW}ℹ️  All secrets were auto-generated${NC}"
echo -e "${YELLOW}ℹ️  Values are ready to use${NC}"
echo ""

echo -e "${BLUE}📝 Next steps:${NC}"
echo "1. Start local services: ${GREEN}./scripts/dev-local.sh${NC}"
echo "2. Run migrations: ${GREEN}pnpm db:migrate${NC}"
echo "3. Start Inngest (separate terminal): ${GREEN}npx inngest-cli@latest dev${NC}"
echo "4. Start API: ${GREEN}pnpm dev:local${NC}"
echo ""
