#!/bin/bash
set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Banner
echo -e "${BLUE}"
echo "╔════════════════════════════════════════════════════════════╗"
echo "║                                                            ║"
echo "║        Synap Demo Mode - Complete Setup                   ║"
echo "║        Backend + Intelligence Service Together            ║"
echo "║                                                            ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

echo -e "${YELLOW}📝 Demo Mode${NC}"
echo "This script sets up BOTH backend and intelligence service on the same server"
echo "All demo users will share this backend"
echo ""

# Detect directory
DEPLOYMENT_ROOT="/srv/synap"

# Domain configuration
echo -e "${BLUE}🌐 Domain Configuration${NC}"
read -p "Enter demo domain (default: demo.synap.live): " DOMAIN
DOMAIN=${DOMAIN:-demo.synap.live}
BACKEND_URL="backend.${DOMAIN}"
APP_URL="app.${DOMAIN}"

echo -e "${GREEN}✓ Backend URL: https://${BACKEND_URL}${NC}"
echo -e "${GREEN}✓ App URL: https://${APP_URL}${NC}"
echo ""

# Generate secrets
echo -e "${BLUE}🔐 Generating Secure Secrets...${NC}"

POSTGRES_PASSWORD=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-32)
KRATOS_COOKIE=$(openssl rand -base64 24 | tr -d "=+/" | cut -c1-32)
KRATOS_CIPHER=$(openssl rand -base64 24 | tr -d "=+/" | cut -c1-32)
KRATOS_WEBHOOK=$(openssl rand -base64 32)
MINIO_PASSWORD=$(openssl rand -base64 32)
INTELLIGENCE_KEY=$(openssl rand -base64 32)
TYPESENSE_KEY=$(openssl rand -base64 32)
TYPESENSE_ADMIN_KEY=$(openssl rand -base64 32)
INNGEST_EVENT=$(openssl rand -base64 32)
INNGEST_SIGNING=$(openssl rand -base64 32)
JWT_SECRET=$(openssl rand -base64 64)

echo -e "${GREEN}✓ All secrets generated${NC}"
echo ""

# Ask for API keys
echo -e "${BLUE}🔑 AI Provider API Keys${NC}"
echo ""

read -p "OpenAI API Key: " OPENAI_KEY
while [ -z "$OPENAI_KEY" ]; do
    echo -e "${RED}OpenAI key is required!${NC}"
    read -p "OpenAI API Key: " OPENAI_KEY
done

read -p "Anthropic API Key (optional): " ANTHROPIC_KEY
read -p "Google AI API Key (optional): " GOOGLE_AI_KEY

echo ""
echo -e "${GREEN}✓ API keys collected${NC}"
echo ""

# Summary
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}📋 Configuration Summary${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo "Mode: DEMO (Shared Backend)"
echo "Domain: ${DOMAIN}"
echo "Backend: https://${BACKEND_URL}"
echo "OpenAI: ${OPENAI_KEY:0:10}..."
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
read -p "Continue with this configuration? (y/n): " CONFIRM
if [[ ! "$CONFIRM" =~ ^[Yy]$ ]]; then
    echo -e "${RED}Setup cancelled${NC}"
    exit 1
fi

# Create directory structure
echo ""
echo -e "${BLUE}📁 Creating directory structure...${NC}"
mkdir -p "${DEPLOYMENT_ROOT}"
mkdir -p "${DEPLOYMENT_ROOT}/synap-backend"
mkdir -p "${DEPLOYMENT_ROOT}/intelligence-service"
mkdir -p "${DEPLOYMENT_ROOT}/data/postgres"
mkdir -p "${DEPLOYMENT_ROOT}/data/typesense"
mkdir -p "${DEPLOYMENT_ROOT}/data/minio"
echo -e "${GREEN}✓ Directories created${NC}"

# Create root .env
echo ""
echo -e "${BLUE}📝 Creating root .env...${NC}"
cat > "${DEPLOYMENT_ROOT}/.env" <<EOF
# Generated by setup-demo.sh on $(date)
# DO NOT COMMIT

# Deployment
DEPLOYMENT_MODE=demo

# Shared Secrets
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
KRATOS_SECRETS_COOKIE=${KRATOS_COOKIE}
KRATOS_SECRETS_CIPHER=${KRATOS_CIPHER}
KRATOS_WEBHOOK_SECRET=${KRATOS_WEBHOOK}
MINIO_SECRET_KEY=${MINIO_PASSWORD}
TYPESENSE_API_KEY=${TYPESENSE_KEY}
TYPESENSE_ADMIN_API_KEY=${TYPESENSE_ADMIN_KEY}
INNGEST_EVENT_KEY=${INNGEST_EVENT}
INNGEST_SIGNING_KEY=${INNGEST_SIGNING}
INTELLIGENCE_API_KEY=${INTELLIGENCE_KEY}
EOF
chmod 600 "${DEPLOYMENT_ROOT}/.env"
echo -e "${GREEN}✓ Root .env created${NC}"

# Create backend .env.production
echo ""
echo -e "${BLUE}📝 Creating backend .env.production...${NC}"
cat > "${DEPLOYMENT_ROOT}/synap-backend/.env.production" <<EOF
# Generated by setup-demo.sh on $(date)
# DO NOT COMMIT

# ============================================================================
# DEPLOYMENT MODE
# ============================================================================
DEPLOYMENT_MODE=demo
NODE_ENV=production
DEMO_MODE_ENABLED=true
DEMO_WORKSPACE_ID=demo-workspace

# ============================================================================
# SERVER CONFIGURATION
# ============================================================================
PORT=4000
REALTIME_PORT=4001
LOG_LEVEL=info

# ============================================================================
# DATABASE
# ============================================================================
DATABASE_URL=postgresql://synap:${POSTGRES_PASSWORD}@postgres:5432/synap

# ============================================================================
# AUTHENTICATION (Ory Kratos + Hydra)
# ============================================================================
KRATOS_PUBLIC_URL=http://kratos:4433
KRATOS_ADMIN_URL=http://kratos:4434
KRATOS_SECRETS_COOKIE=${KRATOS_COOKIE}
KRATOS_SECRETS_CIPHER=${KRATOS_CIPHER}
KRATOS_WEBHOOK_SECRET=${KRATOS_WEBHOOK}

HYDRA_PUBLIC_URL=http://hydra:4444
HYDRA_ADMIN_URL=http://hydra:4445

# ============================================================================
# JWT
# ============================================================================
JWT_SECRET=${JWT_SECRET}

# ============================================================================
# STORAGE (MinIO)
# ============================================================================
STORAGE_PROVIDER=minio
MINIO_ENDPOINT=http://minio:9000
MINIO_ACCESS_KEY=minioadmin
MINIO_SECRET_KEY=${MINIO_PASSWORD}
MINIO_BUCKET=synap-storage
MINIO_USE_SSL=false

# ============================================================================
# AI CONFIGURATION (intelligence Service)
# ============================================================================
# Internal connection (same server)
INTELLIGENCE_HUB_URL=http://intelligence-service:3001
INTELLIGENCE_API_KEY=${INTELLIGENCE_KEY}
OPENAI_API_KEY=${OPENAI_KEY}

# ============================================================================
# SEARCH (Typesense)
# ============================================================================
TYPESENSE_HOST=typesense
TYPESENSE_PORT=8108
TYPESENSE_PROTOCOL=http
TYPESENSE_API_KEY=${TYPESENSE_KEY}
TYPESENSE_ADMIN_API_KEY=${TYPESENSE_ADMIN_KEY}

# ============================================================================
# BACKGROUND JOBS (Inngest)
# ============================================================================
INNGEST_EVENT_KEY=${INNGEST_EVENT}
INNGEST_SIGNING_KEY=${INNGEST_SIGNING}

# ============================================================================
# FRONTEND (CORS)
# ============================================================================
FRONTEND_URL=https://${APP_URL}
ALLOWED_ORIGINS=https://${APP_URL},https://${DOMAIN}
EOF
chmod 600 "${DEPLOYMENT_ROOT}/synap-backend/.env.production"
echo -e "${GREEN}✓ Backend .env.production created${NC}"

# Create intelligence .env.production
echo ""
echo -e "${BLUE}📝 Creating intelligence-service .env.production...${NC}"
cat > "${DEPLOYMENT_ROOT}/intelligence-service/.env.production" <<EOF
# Generated by setup-demo.sh on $(date)
# DO NOT COMMIT

# ============================================================================
# DEPLOYMENT
# ============================================================================
NODE_ENV=production
PORT=3001
LOG_LEVEL=info

# ============================================================================
# AUTHENTICATION
# ============================================================================
API_KEY=${INTELLIGENCE_KEY}

# ============================================================================
# AI PROVIDERS
# ============================================================================
OPENAI_API_KEY=${OPENAI_KEY}
ANTHROPIC_API_KEY=${ANTHROPIC_KEY}
GOOGLE_AI_API_KEY=${GOOGLE_AI_KEY}

# ============================================================================
# BACKEND CONNECTION
# ============================================================================
BACKEND_URL=http://backend:4000
EOF
chmod 600 "${DEPLOYMENT_ROOT}/intelligence-service/.env.production"
echo -e "${GREEN}✓ Intelligence .env.production created${NC}"

# Save secrets backup
echo ""
echo -e "${BLUE}💾 Creating secrets backup...${NC}"
cat > "${DEPLOYMENT_ROOT}/.secrets-backup.txt" <<EOF
# CRITICAL: Save this file securely and DELETE from server!
# Generated: $(date)

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
KRATOS_COOKIE=${KRATOS_COOKIE}
KRATOS_CIPHER=${KRATOS_CIPHER}
MINIO_PASSWORD=${MINIO_PASSWORD}
INTELLIGENCE_KEY=${INTELLIGENCE_KEY}
TYPESENSE_KEY=${TYPESENSE_KEY}
TYPESENSE_ADMIN_KEY=${TYPESENSE_ADMIN_KEY}
INNGEST_EVENT=${INNGEST_EVENT}
INNGEST_SIGNING=${INNGEST_SIGNING}
JWT_SECRET=${JWT_SECRET}

OPENAI_KEY=${OPENAI_KEY}
ANTHROPIC_KEY=${ANTHROPIC_KEY}
GOOGLE_AI_KEY=${GOOGLE_AI_KEY}
EOF
chmod 600 "${DEPLOYMENT_ROOT}/.secrets-backup.txt"
echo -e "${GREEN}✓ Secrets backup created${NC}"

# Success
echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✅ Demo Setup Complete!${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${BLUE}📁 Files Created:${NC}"
echo "  ✓ ${DEPLOYMENT_ROOT}/.env"
echo "  ✓ ${DEPLOYMENT_ROOT}/synap-backend/.env.production"
echo "  ✓ ${DEPLOYMENT_ROOT}/intelligence-service/.env.production"
echo "  ✓ ${DEPLOYMENT_ROOT}/.secrets-backup.txt"
echo ""
echo -e "${YELLOW}📋 Next Steps:${NC}"
echo "  1. Backup .secrets-backup.txt to secure location"
echo "  2. Delete .secrets-backup.txt from server"
echo "  3. Copy docker-compose.yml to ${DEPLOYMENT_ROOT}/"
echo "  4. Start services: cd ${DEPLOYMENT_ROOT} && docker compose up -d"
echo ""
echo -e "${BLUE}🔒 Security:${NC}"
echo "  scp ${DEPLOYMENT_ROOT}/.secrets-backup.txt local:~/"
echo "  rm ${DEPLOYMENT_ROOT}/.secrets-backup.txt"
echo ""
echo -e "${BLUE}🚀 Start Services:${NC}"
echo "  cd ${DEPLOYMENT_ROOT}"
echo "  docker compose up -d"
echo ""
echo -e "${YELLOW}Note: This is for DEMO/TESTING only. For production, use separate scripts.${NC}"
echo ""
